import React from 'react';
import { Activity, BarChart3, Coffee, Gauge, Heart, Sparkles, Target, Timer, Zap } from 'lucide-react';
import { FilterCard, GoalFilter, m, type WorkoutDrinkRecipe, WorkoutDrinksSubcategoryPage } from '../shared';

export const preWorkoutDrinks: WorkoutDrinkRecipe[] = [
  { id: 'pre-1', name: 'Beetroot Nitric Oxide Lift', description: 'Beet juice, citrus, and ginger support blood flow before lifting or intervals.', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop', nutrition: { calories: 110, protein: 2, carbs: 24, fat: 0 }, difficulty: 'Easy', prepTime: 5, rating: 4.8, reviews: 412, trending: true, featured: true, tags: ['Beetroot', 'Nitric oxide', 'Endurance'], bestTime: '60-90 min before training', goal: 'Nitric Oxide Support', fuelType: 'Nitric Oxide', caffeineLevel: 'None', keyIngredient: 'Beetroot', ingredients: ['Beet juice', 'Orange juice', 'Lemon juice', 'Fresh ginger', 'Sea salt'], recipe: { servings: 1, measurements: [m(0.75, 'cup', 'beet juice'), m(0.5, 'cup', 'fresh orange juice'), m(1, 'tbsp', 'fresh lemon juice'), m(0.5, 'tsp', 'grated ginger'), m(1, 'pinch', 'sea salt', 'Sodium helps support fluid retention before sweaty sessions')], directions: ['Add beet juice, orange juice, lemon juice, ginger, and salt to a shaker bottle.', 'Shake hard with a few ice cubes, then strain or sip as-is 60 to 90 minutes before training.'] } },
  { id: 'pre-2', name: 'Cold Brew Citrus Surge', description: 'Cold brew, orange, and honey create a lighter pre-session pick-me-up.', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop', nutrition: { calories: 95, protein: 1, carbs: 19, fat: 0 }, difficulty: 'Easy', prepTime: 4, rating: 4.7, reviews: 355, trending: true, featured: true, tags: ['Cold brew', 'Caffeine', 'Citrus'], bestTime: '30-45 min before training', goal: 'Focus', fuelType: 'Balanced Caffeine', caffeineLevel: 'Moderate (~70mg)', keyIngredient: 'Cold brew coffee', ingredients: ['Cold brew coffee', 'Orange juice', 'Honey', 'Pinch of salt'], recipe: { servings: 1, measurements: [m(0.75, 'cup', 'cold brew coffee'), m(0.25, 'cup', 'fresh orange juice'), m(1, 'tsp', 'honey'), m(1, 'pinch', 'sea salt')], directions: ['Combine cold brew, orange juice, honey, and salt in a jar.', 'Shake until the honey dissolves and serve over ice 30 to 45 minutes before training.'] } },
  { id: 'pre-3', name: 'Banana Oat Carb Smoothie', description: 'Easy-to-digest carbs and a little dairy protein for longer sessions.', image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=400&h=300&fit=crop', nutrition: { calories: 285, protein: 11, carbs: 48, fat: 4 }, difficulty: 'Easy', prepTime: 5, rating: 4.9, reviews: 501, featured: true, tags: ['Banana', 'Oats', 'Carb support'], bestTime: '45-90 min before training', goal: 'Endurance Fuel', fuelType: 'Carb Loading', caffeineLevel: 'None', keyIngredient: 'Rolled oats', ingredients: ['Banana', 'Rolled oats', 'Low-fat milk', 'Greek yogurt', 'Cinnamon'], recipe: { servings: 1, measurements: [m(1, 'small', 'banana'), m(0.33, 'cup', 'rolled oats', 'Blend thoroughly for easier digestion'), m(0.75, 'cup', 'low-fat milk'), m(0.25, 'cup', 'plain Greek yogurt'), m(0.25, 'tsp', 'ground cinnamon')], directions: ['Blend all ingredients until the oats are fully broken down and the smoothie is silky.', 'Drink 45 to 90 minutes before training for a steady carbohydrate release.'] } },
  { id: 'pre-4', name: 'Matcha Maca Focus Blend', description: 'Matcha and maca pair gentle caffeine with earthy adaptogenic flavor.', image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=300&fit=crop', nutrition: { calories: 140, protein: 4, carbs: 19, fat: 5 }, difficulty: 'Easy', prepTime: 4, rating: 4.6, reviews: 244, tags: ['Matcha', 'Maca', 'Focus'], bestTime: '30-60 min before training', goal: 'Focus', fuelType: 'Balanced Caffeine', caffeineLevel: 'Moderate (~70mg)', keyIngredient: 'Matcha', ingredients: ['Matcha', 'Maca powder', 'Unsweetened oat milk', 'Date', 'Vanilla'], recipe: { servings: 1, measurements: [m(1, 'tsp', 'matcha powder'), m(1, 'tsp', 'maca powder'), m(1, 'cup', 'unsweetened oat milk'), m(1, 'small', 'Medjool date, pitted'), m(0.25, 'tsp', 'vanilla extract')], directions: ['Blend or froth matcha, maca, oat milk, date, and vanilla until smooth.', 'Serve chilled or lightly warmed before mobility work, circuits, or technique sessions.'] } },
  { id: 'pre-5', name: 'Watermelon Citrulline Punch', description: 'Hydrating watermelon and lime mimic the food-first spirit of a pre-workout punch.', image: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&h=300&fit=crop', nutrition: { calories: 90, protein: 1, carbs: 21, fat: 0 }, difficulty: 'Easy', prepTime: 5, rating: 4.8, reviews: 286, trending: true, tags: ['Watermelon', 'Citrulline', 'Hydrating'], bestTime: '30-60 min before training', goal: 'Power Output', fuelType: 'Nitric Oxide', caffeineLevel: 'None', keyIngredient: 'Watermelon', ingredients: ['Watermelon', 'Lime juice', 'Mint', 'Sea salt'], recipe: { servings: 1, measurements: [m(1.5, 'cup', 'seedless watermelon cubes'), m(1, 'tbsp', 'fresh lime juice'), m(4, 'leaves', 'mint'), m(1, 'pinch', 'sea salt')], directions: ['Blend watermelon, lime juice, mint, and salt until slushy.', 'Pour over ice and drink before heat sessions or long conditioning blocks.'] } },
  { id: 'pre-6', name: 'Espresso Banana Fuel', description: 'A compact coffee-banana shake for early-morning lifters who need quick energy.', image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop', nutrition: { calories: 210, protein: 9, carbs: 31, fat: 5 }, difficulty: 'Easy', prepTime: 4, rating: 4.7, reviews: 333, featured: true, tags: ['Espresso', 'Banana', 'Quick energy'], bestTime: '30 min before training', goal: 'Power Output', fuelType: 'Balanced Caffeine', caffeineLevel: 'High (~150mg)', keyIngredient: 'Espresso', ingredients: ['Espresso', 'Banana', 'Milk', 'Peanut butter'], recipe: { servings: 1, measurements: [m(2, 'shot', 'espresso, cooled'), m(1, 'small', 'banana'), m(0.75, 'cup', '2% milk'), m(1, 'tbsp', 'natural peanut butter')], directions: ['Blend cooled espresso, banana, milk, and peanut butter until foamy.', 'Sip 20 to 30 minutes before training when you want caffeine plus quick carbohydrate support.'] } },
];

const typeCards: FilterCard[] = [
  { id: 'nitric-oxide', name: 'Nitric Oxide', description: 'Beetroot and watermelon support blood flow and perceived endurance.', icon: Gauge, detailA: 'Best for', detailAValue: 'Strength + endurance days', detailB: 'Timing', detailBValue: '60-90 min before' },
  { id: 'balanced-caffeine', name: 'Balanced Caffeine', description: 'Coffee and matcha pair alertness with carbs or theanine.', icon: Coffee, detailA: 'Best for', detailAValue: 'Focus and tempo work', detailB: 'Timing', detailBValue: '30-60 min before' },
  { id: 'carb-loading', name: 'Carb Loading', description: 'Banana and oats top off glycogen for longer efforts.', icon: BarChart3, detailA: 'Best for', detailAValue: 'Intervals and long sessions', detailB: 'Timing', detailBValue: '45-90 min before' },
];

const goalFilters: GoalFilter[] = [
  { id: 'power-output', name: 'Power Output', icon: Zap, color: 'text-orange-600' },
  { id: 'nitric-oxide', name: 'Nitric Oxide Support', icon: Activity, color: 'text-red-600' },
  { id: 'endurance-fuel', name: 'Endurance Fuel', icon: BarChart3, color: 'text-amber-600' },
  { id: 'focus', name: 'Focus', icon: Target, color: 'text-yellow-600' },
];

export default function PreWorkoutDrinksPage() {
  return <WorkoutDrinksSubcategoryPage title="Pre-Workout Drinks" backHref="/drinks/workout-drinks" backLabel="Back to Workout Drinks" badgeText="Orange Fuel" shareText="Explore ChefSire pre-workout drinks for blood flow, carbs, and smart caffeine." accent="orange" icon={Timer} sourceRoute="/drinks/workout-drinks/pre-workout" recipes={preWorkoutDrinks} typeTabLabel="Fuel Types" typeLabel="Fuel Types" typeField="fuelType" typeCards={typeCards} goalFilters={goalFilters} crossSubcategories={[{ id: 'post-workout', name: 'Post-Workout', description: 'Protein and recovery blends', route: '/drinks/workout-drinks/post-workout', icon: Heart }, { id: 'hydration', name: 'Hydration', description: 'Electrolyte-focused drinks', route: '/drinks/workout-drinks/hydration', icon: Activity }, { id: 'energy-boosters', name: 'Energy Boosters', description: 'Adaptogens and nootropics', route: '/drinks/workout-drinks/energy-boosters', icon: Sparkles }]} stats={{ first: { value: 'Moderate', label: 'Typical Caffeine', color: 'text-orange-600' }, second: { value: '4.7★', label: 'Avg Rating', color: 'text-green-600' }, third: { value: '4 min', label: 'Avg Prep', color: 'text-purple-600' } }} searchPlaceholder="Search pre-workout drinks..." primaryStat={{ label: 'Protein', key: 'nutrition.protein', color: 'text-orange-600', suffix: 'g' }} footer={{ labelA: 'Caffeine', keyA: 'caffeineLevel', colorA: 'text-orange-600', labelB: 'Key Ingredient', keyB: 'keyIngredient', colorB: 'text-red-600' }} buttonLabel="Mix This Fuel" />;
}
