import { sql } from "drizzle-orm";
import {
  pgTable,
  text,
  varchar,
  integer,
  boolean,
  timestamp,
  jsonb,
  decimal,
  index,
} from "drizzle-orm/pg-core";

export const users = pgTable(
  "users",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    username: text("username").notNull().unique(),
    email: text("email").notNull().unique(),
    password: text("password"),
    displayName: text("display_name").notNull(),
    firstName: text("first_name"),
    lastName: text("last_name"),
    royalTitle: text("royal_title"),
    showFullName: boolean("show_full_name").default(false),
    bio: text("bio"),
    avatar: text("avatar"),
    isPrivate: boolean("is_private").default(false),
    specialty: text("specialty"),
    isChef: boolean("is_chef").default(false),
    followersCount: integer("followers_count").default(0),
    followingCount: integer("following_count").default(0),
    postsCount: integer("posts_count").default(0),
    cateringEnabled: boolean("catering_enabled").default(false),
    cateringLocation: text("catering_location"),
    cateringRadius: integer("catering_radius").default(25),
    cateringBio: text("catering_bio"),
    cateringAvailable: boolean("catering_available").default(true),
    subscriptionTier: text("subscription_tier").default("free"),
    subscriptionStatus: text("subscription_status").default("active"),
    subscriptionEndsAt: timestamp("subscription_ends_at"),
    monthlyRevenue: decimal("monthly_revenue", { precision: 10, scale: 2 }).default("0"),
    nutritionPremium: boolean("nutrition_premium").default(false),
    nutritionTrialEndsAt: timestamp("nutrition_trial_ends_at"),
    weddingTier: text("wedding_tier").default("free"),
    weddingStatus: text("wedding_status").default("inactive"),
    weddingEndsAt: timestamp("wedding_ends_at"),
    vendorTier: text("vendor_tier").default("free"),
    vendorStatus: text("vendor_status").default("inactive"),
    vendorEndsAt: timestamp("vendor_ends_at"),
    dailyCalorieGoal: integer("daily_calorie_goal"),
    macroGoals: jsonb("macro_goals").$type<{ protein: number; carbs: number; fat: number }>(),
    dietaryRestrictions: jsonb("dietary_restrictions").$type<string[]>().default(sql`'[]'::jsonb`),
    googleId: text("google_id"),
    facebookId: text("facebook_id"),
    instagramId: text("instagram_id"),
    tiktokId: text("tiktok_id"),
    provider: text("provider"),
    emailVerifiedAt: timestamp("email_verified_at"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => ({
    cateringLocationIdx: index("catering_location_idx").on(table.cateringLocation),
    subscriptionTierIdx: index("subscription_tier_idx").on(table.subscriptionTier),
    googleIdIdx: index("google_id_idx").on(table.googleId),
    facebookIdIdx: index("facebook_id_idx").on(table.facebookId),
    instagramIdIdx: index("instagram_id_idx").on(table.instagramId),
    tiktokIdIdx: index("tiktok_id_idx").on(table.tiktokId),
  })
);
