import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Loader2, Trash2 } from "lucide-react";
import type { AvailabilityException, AvailabilitySettings, WeeklyRule } from "@shared/catering-availability";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/hooks/use-toast";

type Data = { settings: AvailabilitySettings; rules: WeeklyRule[]; exceptions: AvailabilityException[] };
const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export function AvailabilityManager({ providerId, enabled }: { providerId: string; enabled: boolean }) {
  const client = useQueryClient(), { toast } = useToast();
  const query = useQuery({ queryKey: ["catering", "availability", providerId], queryFn: async (): Promise<Data> => { const r = await fetch(`/api/catering/users/${providerId}/availability`, { credentials: "include" }); if (!r.ok) throw new Error("Unable to load availability"); return r.json(); }, enabled });
  const [range, setRange] = useState({ startDate: "", endDate: "", type: "blocked" as "blocked" | "available", reason: "" });
  const request = useMutation({ mutationFn: async ({ url, method, body }: { url: string; method: string; body?: unknown }) => { const r = await fetch(url, { method, credentials: "include", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.message || "Availability was not saved"); }, onSuccess: () => client.invalidateQueries({ queryKey: ["catering", "availability", providerId] }), onError: (error: Error) => toast({ title: "Availability not saved", description: error.message, variant: "destructive" }) });
  if (!enabled) return null;
  if (query.isLoading || !query.data) return <Card><CardContent className="p-6"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Loading availability…</CardContent></Card>;
  const { settings, rules, exceptions } = query.data;
  const saveSettings = (next: AvailabilitySettings) => request.mutate({ url: `/api/catering/users/${providerId}/availability/settings`, method: "PUT", body: next });
  const ruleMap = new Map(rules.map((rule) => [rule.dayOfWeek, rule.available]));
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5" />Availability</CardTitle><CardDescription>Inquiry dates are requests only and are not confirmed bookings.</CardDescription></CardHeader><CardContent className="space-y-6">
    <div className="flex items-center justify-between gap-4"><div><Label>Accepting inquiries</Label><p className="text-sm text-muted-foreground">Immediately pause all new quote requests.</p></div><Switch checked={settings.acceptingBookings} onCheckedChange={(acceptingBookings) => saveSettings({ ...settings, acceptingBookings })} /></div>
    <div className="grid gap-4 sm:grid-cols-3"><div><Label htmlFor="lead-days">Minimum lead days</Label><Input id="lead-days" type="number" min={0} max={1095} defaultValue={settings.minimumLeadDays} onBlur={(e) => saveSettings({ ...settings, minimumLeadDays: Number(e.target.value) })} /></div><div><Label htmlFor="advance-days">Maximum advance days</Label><Input id="advance-days" type="number" min={0} max={1095} defaultValue={settings.maximumAdvanceDays} onBlur={(e) => saveSettings({ ...settings, maximumAdvanceDays: Number(e.target.value) })} /></div><div><Label htmlFor="timezone">Business timezone</Label><Input id="timezone" defaultValue={settings.timezone} onBlur={(e) => saveSettings({ ...settings, timezone: e.target.value })} /></div></div>
    <div><Label>Weekly availability</Label><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{DAYS.map((day, dayOfWeek) => <label key={day} className="flex items-center justify-between rounded border p-2 text-sm">{day}<Switch checked={ruleMap.get(dayOfWeek) !== false} onCheckedChange={(available) => request.mutate({ url: `/api/catering/users/${providerId}/availability/weekly`, method: "PUT", body: { rules: DAYS.map((_, index) => ({ dayOfWeek: index, available: index === dayOfWeek ? available : ruleMap.get(index) !== false })) } })} /></label>)}</div></div>
    <form className="space-y-3 rounded border p-4" onSubmit={(e) => { e.preventDefault(); request.mutate({ url: `/api/catering/users/${providerId}/availability/exceptions`, method: "POST", body: { ...range, endDate: range.endDate || range.startDate, reason: range.reason || null } }); }}><Label>Block dates or add an override</Label><div className="grid gap-3 sm:grid-cols-4"><Input aria-label="Start date" type="date" required value={range.startDate} onChange={(e) => setRange({ ...range, startDate: e.target.value })} /><Input aria-label="End date" type="date" min={range.startDate} value={range.endDate} onChange={(e) => setRange({ ...range, endDate: e.target.value })} /><select className="rounded-md border bg-background px-3" value={range.type} onChange={(e) => setRange({ ...range, type: e.target.value as "blocked" | "available" })}><option value="blocked">Blocked</option><option value="available">Available override</option></select><Button disabled={request.isPending}>Add dates</Button></div><Input placeholder="Private reason (optional)" maxLength={300} value={range.reason} onChange={(e) => setRange({ ...range, reason: e.target.value })} /></form>
    <div><Label>Upcoming exceptions</Label><div className="mt-2 space-y-2">{exceptions.length === 0 ? <p className="text-sm text-muted-foreground">No date exceptions.</p> : exceptions.map((item) => <div key={item.id} className="flex items-center justify-between rounded border p-3 text-sm"><span><strong className={item.type === "blocked" ? "text-red-700" : "text-emerald-700"}>{item.type === "blocked" ? "Blocked" : "Available"}</strong> · {item.startDate}{item.endDate !== item.startDate && ` – ${item.endDate}`}</span><Button variant="ghost" size="icon" aria-label="Remove exception" onClick={() => request.mutate({ url: `/api/catering/users/${providerId}/availability/exceptions/${item.id}`, method: "DELETE" })}><Trash2 className="h-4 w-4" /></Button></div>)}</div></div>
  </CardContent></Card>;
}
