import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Loader2, Star } from "lucide-react";
import type { CateringReviewAggregate, PublicCateringReview } from "@shared/catering-reviews";
import { useUser } from "@/contexts/UserContext";
import { useToast } from "@/hooks/use-toast";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cateringReviewLocalReset, cateringReviewQueryFreshness, cateringReviewQueryKey, cateringReviewViewerKey, clearResponseDraft, customerReviewAction, pageAfterReviewDeletion, responseEditorValue, type CateringReviewForm, type ViewerReview } from "./catering-review-state";

type ReviewResult = { reviews: PublicCateringReview[]; viewerReview: ViewerReview | null; aggregate: CateringReviewAggregate; pagination: { page: number; totalPages: number; total: number } };
const emptyForm: CateringReviewForm = cateringReviewLocalReset().form;

function Stars({ value, onChange }: { value: number; onChange?: (rating: number) => void }) {
  return <div className="flex gap-1" role={onChange ? "radiogroup" : "img"} aria-label={`${value} out of 5 stars`}>
    {[1, 2, 3, 4, 5].map((rating) => <button key={rating} type="button" role={onChange ? "radio" : undefined} aria-checked={onChange ? value === rating : undefined} aria-label={onChange ? `${rating} stars` : undefined} disabled={!onChange} onClick={() => onChange?.(rating)} className="min-h-10 min-w-10 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:min-h-0 disabled:min-w-0 disabled:cursor-default"><Star className={`h-5 w-5 ${rating <= value ? "fill-amber-400 text-amber-500" : "text-muted-foreground"}`} /></button>)}
  </div>;
}

async function responseBody(result: Response) {
  const body = await result.json().catch(() => ({}));
  if (!result.ok) throw new Error(body.message || "The request could not be completed.");
  return body;
}

export function CateringReviews({ providerId, providerMode = false }: { providerId: string; providerMode?: boolean }) {
  const { user, loading } = useUser(); const { toast } = useToast(); const queryClient = useQueryClient();
  const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const [mode, setMode] = useState<"closed" | "create" | "edit">("closed"); const [form, setForm] = useState<CateringReviewForm>(emptyForm);
  const [deleteOpen, setDeleteOpen] = useState(false); const [response, setResponse] = useState<Record<string, string>>({});
  const viewerKey = cateringReviewViewerKey(user?.id);
  const query = useQuery({ queryKey: cateringReviewQueryKey(providerId, viewerKey, sort, page), queryFn: async (): Promise<ReviewResult> => responseBody(await fetch(`/api/catering/providers/${encodeURIComponent(providerId)}/reviews?sort=${sort}&page=${page}&limit=10`, { credentials: "include" })), enabled: !loading, ...cateringReviewQueryFreshness });
  useEffect(() => { const reset = cateringReviewLocalReset(); setMode(reset.mode); setForm(reset.form); setDeleteOpen(reset.deleteOpen); setResponse(reset.responseDrafts); setPage(reset.page); }, [providerId, viewerKey]);
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["catering", "reviews", providerId] });
  const closeForm = () => { setMode("closed"); setForm(emptyForm); };
  const create = useMutation({ mutationFn: async () => responseBody(await fetch("/api/catering/reviews", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerId, ...form, title: form.title || undefined }) })), onSuccess: async () => { closeForm(); setPage(1); await invalidate(); toast({ title: "Review published", description: "Your review is now visible on this provider’s profile." }); } });
  const edit = useMutation({ mutationFn: async () => { if (!query.data?.viewerReview) throw new Error("Your review could not be found."); return responseBody(await fetch(`/api/catering/reviews/${query.data.viewerReview.id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating: form.rating, title: form.title.trim() || null, body: form.body }) })); }, onSuccess: async () => { closeForm(); await invalidate(); toast({ title: "Review updated", description: "Your changes are now public." }); } });
  const remove = useMutation({ mutationFn: async () => { if (!query.data?.viewerReview) throw new Error("Your review could not be found."); const result = await fetch(`/api/catering/reviews/${query.data.viewerReview.id}`, { method: "DELETE", credentials: "include" }); if (!result.ok) await responseBody(result); }, onSuccess: async () => { setDeleteOpen(false); closeForm(); setPage(pageAfterReviewDeletion(page, query.data?.reviews.length ?? 0)); await invalidate(); toast({ title: "Review deleted", description: "You can write a new review at any time." }); }, onError: (error: Error) => toast({ title: "Review was not deleted", description: error.message, variant: "destructive" }) });
  const respond = useMutation({ mutationFn: async ({ id, body }: { id: string; body: string }) => responseBody(await fetch(`/api/catering/reviews/${id}/response`, { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ response: body }) })), onSuccess: async (_data, { id }) => { setResponse((current) => clearResponseDraft(current, id)); await invalidate(); toast({ title: "Response saved", description: "Your response is visible publicly." }); }, onError: (error: Error) => toast({ title: "Response was not saved", description: error.message, variant: "destructive" }) });
  const removeResponse = useMutation({ mutationFn: async (id: string) => { const result = await fetch(`/api/catering/reviews/${id}/response`, { method: "DELETE", credentials: "include" }); if (!result.ok) await responseBody(result); }, onSuccess: async (_data, reviewId) => { setResponse((current) => clearResponseDraft(current, reviewId)); await invalidate(); toast({ title: "Response removed" }); }, onError: (error: Error) => toast({ title: "Response was not removed", description: error.message, variant: "destructive" }) });
  const ownerAction = customerReviewAction({ authLoading: loading, viewerId: user?.id, providerId, viewerReview: query.data?.viewerReview });
  const aggregate = query.data?.aggregate; const submitMutation = mode === "edit" ? edit : create;
  const beginEdit = () => { const review = query.data?.viewerReview; if (!review) return; setForm({ rating: review.rating, title: review.title ?? "", body: review.body }); setMode("edit"); };

  return <section aria-labelledby="catering-reviews-heading" className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="catering-reviews-heading" className="text-xl font-semibold">Reviews</h2>{aggregate?.reviewCount ? <p className="text-sm text-muted-foreground"><strong className="text-foreground">{aggregate.averageRating}</strong> out of 5 · {aggregate.reviewCount} review{aggregate.reviewCount === 1 ? "" : "s"}</p> : <p className="text-sm text-muted-foreground">No reviews yet</p>}</div><div className="flex flex-wrap gap-2">{!providerMode && ownerAction === "create" && <Button onClick={() => { setForm(emptyForm); setMode("create"); }}>Write a review</Button>}{!providerMode && ownerAction === "manage" && <><Button variant="outline" onClick={beginEdit}>Edit review</Button><Button variant="destructive" onClick={() => setDeleteOpen(true)}>Delete review</Button></>}<Label htmlFor="review-sort" className="sr-only">Sort reviews</Label><select id="review-sort" className="h-10 rounded-md border bg-background px-3 text-sm" value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest rated</option><option value="lowest">Lowest rated</option></select></div></div>
    {!providerMode && !loading && !user && <p className="text-sm text-muted-foreground">Sign in to leave a review.</p>}
    {mode !== "closed" && <form className="space-y-4 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); submitMutation.mutate(); }}><h3 className="font-semibold">{mode === "edit" ? "Edit your review" : "Write a review"}</h3><div><Label>Your rating</Label><Stars value={form.rating} onChange={(rating) => setForm({ ...form, rating })} /></div><div><Label htmlFor="review-title">Title (optional)</Label><Input id="review-title" maxLength={120} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div><Label htmlFor="review-body">Your review</Label><Textarea id="review-body" required minLength={10} maxLength={4000} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /><p className="mt-1 text-xs text-muted-foreground">Be honest and specific. Don’t include private contact or event details.</p></div>{submitMutation.error && <p role="alert" className="text-sm text-destructive">{submitMutation.error.message}</p>}<div className="flex gap-2"><Button disabled={submitMutation.isPending || form.rating < 1}>{submitMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{mode === "edit" ? "Save changes" : "Publish review"}</Button><Button type="button" variant="outline" disabled={submitMutation.isPending} onClick={closeForm}>Cancel</Button></div></form>}
    {query.isLoading || loading ? <p role="status">Loading reviews…</p> : query.isError ? <div role="alert" className="flex flex-wrap items-center gap-3 text-destructive"><span>Reviews could not be loaded.</span><Button size="sm" variant="outline" onClick={() => query.refetch()}>Retry</Button></div> : query.data?.reviews.length ? <div className="space-y-4">{query.data.reviews.map((review) => <article key={review.id} className="min-w-0 rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{review.reviewer.displayName}</p><Stars value={review.rating} /></div><time className="text-sm text-muted-foreground" dateTime={review.createdAt}>{new Date(review.createdAt).toLocaleDateString()}</time></div>{review.verifiedEvent && <Badge className="mt-2">Verified event</Badge>}{review.title && <h3 className="mt-3 break-words font-semibold">{review.title}</h3>}<p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{review.body}</p>{review.providerResponse && <div className="mt-4 rounded-md bg-muted p-3"><p className="text-sm font-semibold">Provider response</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{review.providerResponse.body}</p>{providerMode && <Button className="mt-2" size="sm" variant="ghost" disabled={removeResponse.isPending} onClick={() => removeResponse.mutate(review.id)}>Remove response</Button>}</div>}{providerMode && <form className="mt-4 space-y-2" onSubmit={(event) => { event.preventDefault(); respond.mutate({ id: review.id, body: responseEditorValue(response, review.id, review.providerResponse?.body) }); }}><Label htmlFor={`response-${review.id}`}>{review.providerResponse ? "Edit public response" : "Write a public response"}</Label><Textarea id={`response-${review.id}`} minLength={2} maxLength={2000} required value={responseEditorValue(response, review.id, review.providerResponse?.body)} onChange={(event) => setResponse((current) => ({ ...current, [review.id]: event.target.value }))} /><Button size="sm" disabled={respond.isPending}>{respond.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save response</Button></form>}</article>)}</div> : null}
    {(query.data?.pagination.totalPages ?? 0) > 1 && <nav aria-label="Review pages" className="flex items-center justify-between"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</Button><span className="text-sm">Page {page} of {query.data?.pagination.totalPages}</span><Button variant="outline" disabled={page === query.data?.pagination.totalPages} onClick={() => setPage(page + 1)}>Next</Button></nav>}
    <AlertDialog open={deleteOpen} onOpenChange={(open) => { if (!remove.isPending) setDeleteOpen(open); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete your review?</AlertDialogTitle><AlertDialogDescription>This permanently removes your rating, review, and the provider’s response. This action cannot be undone.</AlertDialogDescription></AlertDialogHeader>{remove.error && <p role="alert" className="text-sm text-destructive">{remove.error.message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={remove.isPending}>Cancel</AlertDialogCancel><AlertDialogAction disabled={remove.isPending} onClick={(event) => { event.preventDefault(); remove.mutate(); }} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">{remove.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Delete review</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}
