import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Loader2, Star } from "lucide-react";
import type { PublicCateringReview, CateringReviewAggregate } from "@shared/catering-reviews";
import { useUser } from "@/contexts/UserContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";

type ReviewResult = { reviews: PublicCateringReview[]; aggregate: CateringReviewAggregate; pagination: { page: number; totalPages: number; total: number } };
const key = (providerId: string, sort: string, page: number) => ["catering", "reviews", providerId, sort, page] as const;

function Stars({ value, onChange }: { value: number; onChange?: (rating: number) => void }) {
  return <div className="flex gap-1" role={onChange ? "radiogroup" : "img"} aria-label={`${value} out of 5 stars`}>{[1, 2, 3, 4, 5].map((rating) => <button key={rating} type="button" role={onChange ? "radio" : undefined} aria-checked={onChange ? value === rating : undefined} aria-label={onChange ? `${rating} stars` : undefined} disabled={!onChange} onClick={() => onChange?.(rating)} className="min-h-10 min-w-10 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:min-h-0 disabled:min-w-0 disabled:cursor-default"><Star className={`h-5 w-5 ${rating <= value ? "fill-amber-400 text-amber-500" : "text-muted-foreground"}`} /></button>)}</div>;
}

export function CateringReviews({ providerId, providerMode = false }: { providerId: string; providerMode?: boolean }) {
  const { user, loading } = useUser(); const queryClient = useQueryClient();
  const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1); const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ rating: 0, title: "", body: "" }); const [response, setResponse] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: key(providerId, sort, page), queryFn: async (): Promise<ReviewResult> => { const result = await fetch(`/api/catering/providers/${encodeURIComponent(providerId)}/reviews?sort=${sort}&page=${page}&limit=10`); const body = await result.json(); if (!result.ok) throw new Error(body.message || "Unable to load reviews"); return body; } });
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["catering", "reviews", providerId] });
  const create = useMutation({ mutationFn: async () => { const result = await fetch("/api/catering/reviews", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerId, ...form }) }); const body = await result.json().catch(() => ({})); if (!result.ok) throw new Error(body.message || "Unable to publish review"); }, onSuccess: async () => { setForm({ rating: 0, title: "", body: "" }); setShowForm(false); await invalidate(); } });
  const respond = useMutation({ mutationFn: async ({ id, body }: { id: string; body: string }) => { const result = await fetch(`/api/catering/reviews/${id}/response`, { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ response: body }) }); const data = await result.json().catch(() => ({})); if (!result.ok) throw new Error(data.message || "Unable to save response"); }, onSuccess: invalidate });
  const removeResponse = useMutation({ mutationFn: async (id: string) => { const result = await fetch(`/api/catering/reviews/${id}/response`, { method: "DELETE", credentials: "include" }); if (!result.ok) throw new Error("Unable to remove response"); }, onSuccess: invalidate });
  const aggregate = query.data?.aggregate;
  return <section aria-labelledby="catering-reviews-heading" className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="catering-reviews-heading" className="text-xl font-semibold">Reviews</h2>{aggregate?.reviewCount ? <p className="text-sm text-muted-foreground"><strong className="text-foreground">{aggregate.averageRating}</strong> out of 5 · {aggregate.reviewCount} review{aggregate.reviewCount === 1 ? "" : "s"}</p> : <p className="text-sm text-muted-foreground">No reviews yet</p>}</div><div className="flex flex-wrap gap-2">{!providerMode && !loading && user && user.id !== providerId && <Button onClick={() => setShowForm(!showForm)}>{showForm ? "Cancel" : "Write a review"}</Button>}<Label htmlFor="review-sort" className="sr-only">Sort reviews</Label><select id="review-sort" className="h-10 rounded-md border bg-background px-3 text-sm" value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest rated</option><option value="lowest">Lowest rated</option></select></div></div>
    {!providerMode && !loading && !user && <p className="text-sm text-muted-foreground">Sign in to leave a review.</p>}
    {showForm && <form className="space-y-4 rounded-lg border p-4" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><div><Label>Your rating</Label><Stars value={form.rating} onChange={(rating) => setForm({ ...form, rating })} /></div><div><Label htmlFor="review-title">Title (optional)</Label><Input id="review-title" maxLength={120} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div><Label htmlFor="review-body">Your review</Label><Textarea id="review-body" required minLength={10} maxLength={4000} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /><p className="mt-1 text-xs text-muted-foreground">Be honest and specific. Don’t include private contact or event details.</p></div>{create.error && <p role="alert" className="text-sm text-destructive">{create.error.message}</p>}<Button disabled={create.isPending || form.rating < 1}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Publish review</Button></form>}
    {query.isLoading ? <p role="status">Loading reviews…</p> : query.isError ? <p role="alert" className="text-destructive">Reviews could not be loaded.</p> : query.data?.reviews.length ? <div className="space-y-4">{query.data.reviews.map((review) => <article key={review.id} className="min-w-0 rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{review.reviewer.displayName}</p><Stars value={review.rating} /></div><time className="text-sm text-muted-foreground" dateTime={review.createdAt}>{new Date(review.createdAt).toLocaleDateString()}</time></div>{review.verifiedEvent && <Badge className="mt-2">Verified event</Badge>}{review.title && <h3 className="mt-3 font-semibold break-words">{review.title}</h3>}<p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{review.body}</p>{review.providerResponse && <div className="mt-4 rounded-md bg-muted p-3"><p className="text-sm font-semibold">Provider response</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{review.providerResponse.body}</p>{providerMode && <Button className="mt-2" size="sm" variant="ghost" onClick={() => removeResponse.mutate(review.id)}>Remove response</Button>}</div>}{providerMode && <form className="mt-4 space-y-2" onSubmit={(event) => { event.preventDefault(); respond.mutate({ id: review.id, body: response[review.id] ?? review.providerResponse?.body ?? "" }); }}><Label htmlFor={`response-${review.id}`}>{review.providerResponse ? "Edit public response" : "Write a public response"}</Label><Textarea id={`response-${review.id}`} minLength={2} maxLength={2000} required value={response[review.id] ?? review.providerResponse?.body ?? ""} onChange={(event) => setResponse({ ...response, [review.id]: event.target.value })} /><Button size="sm" disabled={respond.isPending}>Save response</Button></form>}</article>)}</div> : null}
    {(query.data?.pagination.totalPages ?? 0) > 1 && <nav aria-label="Review pages" className="flex items-center justify-between"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</Button><span className="text-sm">Page {page} of {query.data?.pagination.totalPages}</span><Button variant="outline" disabled={page === query.data?.pagination.totalPages} onClick={() => setPage(page + 1)}>Next</Button></nav>}
  </section>;
}
