import { FormEvent, useEffect, useState } from "react";
import { Link, useLocation, useParams } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarDays, CheckCircle2, Circle, ClipboardList, MapPin, Plus, Trash2 } from "lucide-react";
import { useUser } from "@/contexts/UserContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { formatCateringCalendarDate } from "@shared/catering-availability";

type Workspace = { role: "provider" | "customer"; editable: boolean; booking: { id: string; status: string; eventDate: string; eventType: string | null; guestCount: number | null; agreedPrice: string | null; currency: string }; provider: { displayName: string | null } | null; details: Record<string, string | boolean | null> | null; tasks: Array<{ id: string; title: string; description: string | null; status: "pending" | "completed"; visibility: "provider" | "shared"; dueDate: string | null }>; activity: { items: Array<{ id: string; eventType: string; createdAt: string }>; nextCursor: unknown } };
const fields = ["venueName", "venueAddress", "venueCity", "venueState", "venuePostalCode", "venueInstructions", "arrivalTime", "serviceStartTime", "serviceEndTime", "setupNotes", "accessNotes", "providerNotes"] as const;
export const cateringBookingWorkspaceKey = (userId: string, bookingId: string) => ["catering", "booking-workspace", userId, bookingId] as const;
const statusLabel: Record<string, string> = { pending_confirmation: "Pending customer confirmation", confirmed: "Confirmed booking", cancelled: "Cancelled booking", completed: "Completed event" };

export default function CateringBookingWorkspace() {
  const { bookingId = "" } = useParams<{ bookingId: string }>(); const { user, loading } = useUser(); const [, navigate] = useLocation(); const client = useQueryClient();
  useEffect(() => { if (!loading && !user) navigate(`/login?next=${encodeURIComponent(location.pathname)}`, { replace: true }); }, [loading, navigate, user]);
  const key = cateringBookingWorkspaceKey(user?.id ?? "anonymous", bookingId);
  const query = useQuery({ queryKey: key, enabled: Boolean(user && bookingId), staleTime: 30_000, queryFn: async (): Promise<Workspace> => { const response = await fetch(`/api/catering/bookings/${bookingId}/workspace`, { credentials: "include" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Event workspace could not be loaded"); return body; } });
  const workspace = query.data; const [details, setDetails] = useState<Record<string, string | boolean | null>>({}); const [task, setTask] = useState({ title: "", description: "", visibility: "provider" });
  useEffect(() => { if (workspace?.details) setDetails(workspace.details); }, [workspace?.details]);
  const request = useMutation({ mutationFn: async ({ url, method, body }: { url: string; method: string; body?: unknown }) => { const response = await fetch(url, { method, credentials: "include", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "Change could not be saved"); }, onSuccess: () => client.invalidateQueries({ queryKey: key }) });
  if (loading || query.isLoading) return <main className="mx-auto max-w-5xl p-4" role="status">Loading event workspace…</main>;
  if (query.isError || !workspace) return <main className="mx-auto max-w-5xl space-y-4 p-4"><p role="alert">{query.error?.message || "Event workspace not found"}</p><Button variant="outline" onClick={() => query.refetch()}>Retry</Button></main>;
  const isProvider = workspace.role === "provider";
  const saveDetails = (event: FormEvent) => { event.preventDefault(); const allowed = isProvider ? details : { customerNotes: details.customerNotes ?? null }; request.mutate({ url: `/api/catering/bookings/${bookingId}/details`, method: "PUT", body: allowed }); };
  return <main className="mx-auto max-w-5xl space-y-6 overflow-x-hidden p-4 sm:p-6">
    <Link href={isProvider ? "/services/catering/provider" : "/services/catering"}><Button variant="ghost" className="min-h-11"><ArrowLeft className="mr-2 h-4 w-4" />Back to catering</Button></Link>
    <header><p className="text-sm font-medium text-orange-700">{statusLabel[workspace.booking.status] || workspace.booking.status}</p><h1 className="text-2xl font-bold sm:text-3xl">{workspace.booking.eventType || "Catering event"}</h1><p className="mt-1 text-muted-foreground">{isProvider ? "Manage operational planning without changing the booking agreement." : `Event with ${workspace.provider?.displayName || "your caterer"}.`}</p>{!workspace.editable && <p className="mt-3 rounded-md border bg-muted p-3 text-sm">This historical workspace is read-only.</p>}</header>
    <section className="grid gap-4 sm:grid-cols-3" aria-label="Booking overview"><Card><CardContent className="flex gap-3 pt-6"><CalendarDays /><div><p className="font-medium">Event date</p><p>{formatCateringCalendarDate(workspace.booking.eventDate)}</p></div></CardContent></Card><Card><CardContent className="pt-6"><p className="font-medium">Guests</p><p>{workspace.booking.guestCount ?? "Not specified"}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="font-medium">Agreement price</p><p>{workspace.booking.agreedPrice ? `${workspace.booking.currency} ${workspace.booking.agreedPrice}` : "Not specified"}</p></CardContent></Card></section>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin />Event details</CardTitle><CardDescription>Times are event-local wall-clock times. Agreement date, guests, and price cannot be changed here.</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={saveDetails}>{fields.filter((name) => isProvider || name !== "providerNotes").map((name) => <div key={name} className={name.includes("Notes") || name.includes("Instructions") ? "sm:col-span-2" : ""}><Label htmlFor={name}>{name.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase())}{name === "providerNotes" ? " (private)" : ""}</Label>{name.includes("Notes") || name.includes("Instructions") ? <Textarea id={name} disabled={!workspace.editable} value={String(details[name] ?? "")} onChange={(event) => setDetails({ ...details, [name]: event.target.value || null })} /> : <Input id={name} type={name.includes("Time") ? "time" : "text"} disabled={!workspace.editable} value={String(details[name] ?? "")} onChange={(event) => setDetails({ ...details, [name]: event.target.value || null })} />}</div>)}{!isProvider && <div className="sm:col-span-2"><Label htmlFor="customerNotes">Notes for your caterer</Label><Textarea id="customerNotes" disabled={!workspace.editable} value={String(details.customerNotes ?? "")} onChange={(event) => setDetails({ ...details, customerNotes: event.target.value || null })} /></div>}{workspace.editable && <Button disabled={request.isPending} className="min-h-11 sm:col-span-2" type="submit">Save event details</Button>}</form></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardList />{isProvider ? "Checklist and customer requirements" : "Things your caterer needs from you"}</CardTitle><CardDescription>{isProvider ? "Provider-only checklist items stay private; shared items are published as customer requirements." : "Only requirements explicitly shared by your caterer appear here."}</CardDescription></CardHeader><CardContent className="space-y-4">{workspace.tasks.length ? <ul className="space-y-2">{workspace.tasks.map((item) => <li key={item.id} className="flex min-w-0 items-center gap-3 rounded-lg border p-3"><Button aria-label={`${item.status === "completed" ? "Mark incomplete" : "Mark complete"}: ${item.title}`} variant="ghost" size="icon" disabled={!isProvider || !workspace.editable || request.isPending} onClick={() => request.mutate({ url: `/api/catering/bookings/${bookingId}/tasks/${item.id}`, method: "PATCH", body: { status: item.status === "completed" ? "pending" : "completed" } })}>{item.status === "completed" ? <CheckCircle2 /> : <Circle />}</Button><div className="min-w-0 flex-1"><p className="break-words font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.visibility === "shared" ? "Shared requirement" : "Provider private"}{item.dueDate ? ` · Due ${formatCateringCalendarDate(item.dueDate)}` : ""}</p></div>{isProvider && workspace.editable && <Button aria-label={`Delete ${item.title}`} variant="ghost" size="icon" onClick={() => { if (window.confirm(`Delete “${item.title}”?`)) request.mutate({ url: `/api/catering/bookings/${bookingId}/tasks/${item.id}`, method: "DELETE" }); }}><Trash2 /></Button>}</li>)}</ul> : <p className="rounded-lg border border-dashed p-6 text-center text-muted-foreground">{isProvider ? "No checklist items or customer requirements yet." : "Your caterer has not published any preparation requirements."}</p>}{isProvider && workspace.editable && <form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); request.mutate({ url: `/api/catering/bookings/${bookingId}/tasks`, method: "POST", body: task }); setTask({ title: "", description: "", visibility: "provider" }); }}><div><Label htmlFor="task-title">Task title</Label><Input id="task-title" required maxLength={160} value={task.title} onChange={(event) => setTask({ ...task, title: event.target.value })} /></div><div><Label htmlFor="task-visibility">Visibility</Label><select id="task-visibility" className="flex min-h-10 w-full rounded-md border bg-background px-3" value={task.visibility} onChange={(event) => setTask({ ...task, visibility: event.target.value })}><option value="provider">Provider private</option><option value="shared">Customer requirement</option></select></div><Button disabled={request.isPending} type="submit" className="min-h-11 sm:col-span-2"><Plus className="mr-2" />Add item</Button></form>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Booking activity</CardTitle><CardDescription>Meaningful shared changes, newest first.</CardDescription></CardHeader><CardContent>{workspace.activity.items.length ? <ol className="space-y-3">{workspace.activity.items.map((item) => <li key={item.id} className="border-l-2 pl-3"><p>{item.eventType.replaceAll("_", " ")}</p><time className="text-xs text-muted-foreground" dateTime={item.createdAt}>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</time></li>)}</ol> : <p className="text-muted-foreground">No workspace activity has been recorded yet.</p>}</CardContent></Card>
    {request.isError && <p className="text-destructive" role="alert">{request.error.message}</p>}
  </main>;
}
