import { useMemo } from 'react';
import { buildPlannerDashboardViewModel } from '@/components/meal-planner/view-models';

type UsePlannerDashboardInput = Omit<
  Parameters<typeof buildPlannerDashboardViewModel>[0],
  'sharePublicToken'
> & {
  sharePublicToken?: string | null;
};

export const usePlannerDashboard = ({
  caloriesCurrent,
  proteinCurrent,
  carbsCurrent,
  fatCurrent,
  calorieGoal,
  macroGoals,
  shareVisibility,
  weekRange,
  weekAnchor,
  sharePublicToken,
  origin,
  plannedSlots,
  totalSlots,
  weeklyMealsCount,
  weekReadyNow,
  groceryCompletedCount,
  groceryBuyItemCount,
  prepProgress,
  prepTasksCompletedCount,
  prepTasksCount,
  prepActiveBlockersCount,
  avgCalories,
  avgProtein,
  proteinGoalHitDays,
  calorieGoalHitDays,
  water,
  hydrationPct,
  latestBodyMetric,
  bodyWeightDelta,
}: UsePlannerDashboardInput) =>
  useMemo(
    () =>
      buildPlannerDashboardViewModel({
        caloriesCurrent,
        proteinCurrent,
        carbsCurrent,
        fatCurrent,
        calorieGoal,
        macroGoals,
        shareVisibility,
        weekRange,
        weekAnchor,
        sharePublicToken: sharePublicToken ?? undefined,
        origin,
        plannedSlots,
        totalSlots,
        weeklyMealsCount,
        weekReadyNow,
        groceryCompletedCount,
        groceryBuyItemCount,
        prepProgress,
        prepTasksCompletedCount,
        prepTasksCount,
        prepActiveBlockersCount,
        avgCalories,
        avgProtein,
        proteinGoalHitDays,
        calorieGoalHitDays,
        water,
        hydrationPct,
        latestBodyMetric,
        bodyWeightDelta,
      }),
    [
      avgCalories,
      avgProtein,
      bodyWeightDelta,
      calorieGoal,
      calorieGoalHitDays,
      caloriesCurrent,
      carbsCurrent,
      fatCurrent,
      groceryBuyItemCount,
      groceryCompletedCount,
      hydrationPct,
      latestBodyMetric,
      macroGoals,
      origin,
      plannedSlots,
      prepActiveBlockersCount,
      prepProgress,
      prepTasksCompletedCount,
      prepTasksCount,
      proteinCurrent,
      proteinGoalHitDays,
      sharePublicToken,
      shareVisibility,
      totalSlots,
      water,
      weekAnchor,
      weekReadyNow,
      weekRange,
      weeklyMealsCount,
    ],
  );
