import { z } from "zod";

/**
 * PHASE 2P -- POST-CONFIRMATION BILLING ADJUSTMENTS, CREDITS AND EXTERNAL REFUND RECORDS.
 *
 * One place where the server, the client and the tests agree on what a LATER financial change to a catering booking
 * means. No React, no fetch, no database and no clock: every rule below is a function over plain facts, tested exactly
 * as both sides run it.
 *
 * THE ACCOUNTING PRINCIPLE. Historical financial evidence is never rewritten because commercial terms changed. An
 * invoice issued for 500.00 stays 500.00; a recorded payment stays recorded after a refund is recorded against it.
 * Later changes are explicit rows in an append-only adjustment ledger, and the current position is a derivation:
 *
 *     original obligation + additional charges - credits  =  current obligation
 *     payments recorded   - refunds recorded              =  net received
 *     current obligation  - net received                  =  balance due (or refund potentially due, if negative)
 *
 * THREE CONCEPTS, deliberately never collapsed into one number:
 *
 *  - CHARGE   the customer owes more. It is a statement of obligation, not of payment: it is never marked paid by
 *             being posted, and it never edits an invoice. It is collected the way everything else is, by a request
 *             for payment (an `adjustment` invoice) and the payments the provider records against it.
 *  - CREDIT   the customer's obligation is reduced. It is NOT evidence that money was returned.
 *  - REFUND   money that was ALREADY RECORDED as received was returned OUTSIDE ChefSire. It is a record of a fact the
 *             provider states, not an instruction, and ChefSire sends nothing. It reduces net received and does not
 *             touch the obligation, so a credit and a refund for the same money are two honest facts, not a double count.
 *
 * ChefSire executes no payment processor action in this phase and fabricates no transaction identifier.
 *
 * WHERE THE AGREED PRICE FITS. `catering_bookings.agreed_price` stays the authoritative CURRENT agreed price, and a
 * Phase 2O amendment that changes it after billing began writes an `amendment`-sourced entry in the SAME transaction
 * that accepts it. That entry EXPLAINS a movement the agreed price already contains, so it is displayed but never added
 * a second time. Only `provider_recorded` entries move the obligation away from the agreed price:
 *
 *     current obligation = agreed price + provider charges - provider credits
 *     original agreed    = agreed price - (amendment charges - amendment credits)
 *
 * which makes `original agreed + all charges - all credits` equal the current obligation, whichever source an entry has.
 *
 * CORRECTIONS. A posted entry is never edited or deleted. A mistaken provider entry is REVERSED: it stays visible
 * with its reason, and stops counting. An entry generated by an accepted amendment cannot be reversed here, because
 * the amendment is the agreement behind it; a further amendment is how that is corrected.
 */

export const CATERING_ADJUSTMENT_KINDS = ["charge", "credit", "refund"] as const;
export type CateringAdjustmentKind = typeof CATERING_ADJUSTMENT_KINDS[number];

/** `provider_recorded` is entered by the provider; `amendment` is written by the acceptance of a Phase 2O amendment. */
export const CATERING_ADJUSTMENT_SOURCES = ["provider_recorded", "amendment"] as const;
export type CateringAdjustmentSource = typeof CATERING_ADJUSTMENT_SOURCES[number];

/** Two persisted states. A reversed entry is kept for audit and counts for nothing. */
export const CATERING_ADJUSTMENT_STATUSES = ["posted", "reversed"] as const;
export type CateringAdjustmentStatus = typeof CATERING_ADJUSTMENT_STATUSES[number];

export const CATERING_ADJUSTMENT_MAXIMUM_CENTS = 99_999_999_99;
export const CATERING_ADJUSTMENT_REASON_MAX_LENGTH = 500;
export const CATERING_ADJUSTMENT_REFERENCE_MAX_LENGTH = 64;

export type CateringAdjustmentFact = {
  id: string;
  kind: CateringAdjustmentKind;
  amountCents: number;
  currency: string;
  status: CateringAdjustmentStatus;
  source: CateringAdjustmentSource;
  paymentId: string | null;
};

export const cateringAdjustmentCounts = (entry: Pick<CateringAdjustmentFact, "status">) => entry.status === "posted";

/* ------------------------------------------------------------------------------------------------------------- *
 * Derivation
 * ------------------------------------------------------------------------------------------------------------- */

export type CateringLedgerPosition = {
  /** Every posted charge / credit, whatever its source: what the history shows. */
  chargesCents: number;
  creditsCents: number;
  /** Posted entries recorded by the provider: the ones that move the obligation away from the agreed price. */
  providerChargesCents: number;
  providerCreditsCents: number;
  /** Posted amendment-generated charges less credits: already contained in the agreed price. */
  amendmentNetCents: number;
  refundsCents: number;
  /** The agreed price before any amendment that was reconciled into the ledger. Null without an agreed price. */
  originalAgreedCents: number | null;
  /** What the customer owes in total right now. Null without an agreed price. */
  obligationCents: number | null;
  netReceivedCents: number;
  /** Obligation less net received, floored at zero. Null without an agreed price. */
  balanceDueCents: number | null;
  /** Net received above the obligation: money the customer may be owed back. A prompt, never a claim a refund happened. */
  refundPotentiallyDueCents: number;
};

function sumPosted(entries: readonly CateringAdjustmentFact[], kind: CateringAdjustmentKind, source?: CateringAdjustmentSource): number {
  return entries.reduce((total, entry) => (cateringAdjustmentCounts(entry) && entry.kind === kind && (source === undefined || entry.source === source) ? total + entry.amountCents : total), 0);
}

/** The ONE derivation of the ledger's position. Nothing here is persisted and nothing is computed in React. */
export function deriveCateringLedgerPosition(input: { agreedTotalCents: number | null; paidTotalCents: number; adjustments: readonly CateringAdjustmentFact[] }): CateringLedgerPosition {
  const { adjustments } = input;
  const providerChargesCents = sumPosted(adjustments, "charge", "provider_recorded");
  const providerCreditsCents = sumPosted(adjustments, "credit", "provider_recorded");
  const amendmentNetCents = sumPosted(adjustments, "charge", "amendment") - sumPosted(adjustments, "credit", "amendment");
  const refundsCents = sumPosted(adjustments, "refund");
  const agreed = input.agreedTotalCents;
  const obligationCents = agreed === null ? null : agreed + providerChargesCents - providerCreditsCents;
  const netReceivedCents = input.paidTotalCents - refundsCents;
  return {
    chargesCents: sumPosted(adjustments, "charge"),
    creditsCents: sumPosted(adjustments, "credit"),
    providerChargesCents, providerCreditsCents, amendmentNetCents, refundsCents,
    originalAgreedCents: agreed === null ? null : agreed - amendmentNetCents,
    obligationCents,
    netReceivedCents,
    balanceDueCents: obligationCents === null ? null : Math.max(0, obligationCents - netReceivedCents),
    refundPotentiallyDueCents: obligationCents === null ? 0 : Math.max(0, netReceivedCents - obligationCents),
  };
}

/* ------------------------------------------------------------------------------------------------------------- *
 * What each booking status permits
 * ------------------------------------------------------------------------------------------------------------- */

/**
 * Which kinds a provider may RECORD, by the booking's own status (which this phase reads and never writes).
 *
 *  - pending_confirmation: refunds only. The price is still being negotiated through offers (Phase 2N), so a charge or a
 *    credit here would be a unilateral price change that bypasses the customer's acceptance; but a deposit already
 *    received can legitimately be returned.
 *  - confirmed: everything. Price changes the customer agreed to arrive as amendments; the rest is the provider's call.
 *  - completed: credits and refunds. Late reconciliation is real; a NEW charge after the event, with no agreement that
 *    can still be reached, is not.
 *  - cancelled: refunds only. Cancellation invents no fee and no credit, and money received for an event that will not
 *    happen is exactly what gets returned.
 */
const RECORDABLE: Record<string, readonly CateringAdjustmentKind[]> = {
  pending_confirmation: ["refund"],
  confirmed: ["charge", "credit", "refund"],
  completed: ["credit", "refund"],
  cancelled: ["refund"],
};
/** Which kinds may be REVERSED. Undoing a charge only lowers the obligation and undoing a refund only restores a recorded fact. */
const REVERSIBLE: Record<string, readonly CateringAdjustmentKind[]> = {
  pending_confirmation: ["refund"],
  confirmed: ["charge", "credit", "refund"],
  completed: ["charge", "refund"],
  cancelled: ["refund"],
};

export const cateringAdjustmentKindsRecordable = (bookingStatus: string): readonly CateringAdjustmentKind[] => RECORDABLE[bookingStatus] ?? [];
export const cateringAdjustmentKindsReversible = (bookingStatus: string): readonly CateringAdjustmentKind[] => REVERSIBLE[bookingStatus] ?? [];

/* ------------------------------------------------------------------------------------------------------------- *
 * Write rules
 * ------------------------------------------------------------------------------------------------------------- */

export type CateringAdjustmentFacts = {
  bookingStatus: string;
  currency: string;
  agreedTotalCents: number | null;
  /** Live (issued, not void) invoice totals, and the payments recorded against everything. */
  liveInvoicedCents: number;
  paidTotalCents: number;
  /** Per-payment: recorded amount and the currency it was recorded in, for a refund that names one. */
  payments: readonly { id: string; amountCents: number; currency: string; status: "recorded" | "voided" }[];
  adjustments: readonly CateringAdjustmentFact[];
};

export type CateringAdjustmentRefusal = { ok: false; code: CateringAdjustmentRefusalCode; message: string };
export type CateringAdjustmentRefusalCode = "not_allowed_for_status" | "no_agreed_price" | "currency_mismatch" | "exceeds_obligation" | "exceeds_received" | "payment_not_found" | "payment_exceeds" | "invoice_outstanding" | "not_reversible" | "already_reversed";

const refuse = (code: CateringAdjustmentRefusalCode, message: string): CateringAdjustmentRefusal => ({ ok: false, code, message });

export const CATERING_ADJUSTMENT_REFUSAL_COPY = {
  statusKind: (kind: CateringAdjustmentKind, status: string) => status === "cancelled"
    ? "This booking was cancelled. Only a record of money returned to your customer can be added now."
    : status === "completed"
      ? (kind === "charge" ? "This event is complete, so a new charge can no longer be added. You can still record a credit or a refund." : "That cannot be recorded against this booking in its current state.")
      : status === "pending_confirmation"
        ? "This booking has not been confirmed yet. Its price is changed through the offer, not by an adjustment. You can still record a refund of money already received."
        : "That cannot be recorded against this booking in its current state.",
  noAgreedPrice: "This booking has no agreed price, so there is nothing to add a charge or credit to.",
  currency: "That amount is in a different currency from this booking. ChefSire does not convert between currencies.",
  creditTooLarge: "A credit cannot be more than what your customer currently owes for this booking.",
  refundTooLarge: "A refund record cannot be more than the money already recorded as received and not yet recorded as returned.",
  paymentNotFound: "That payment is not recorded on this booking.",
  paymentTooLarge: "A refund record against a payment cannot be more than that payment, less refunds already recorded against it.",
  invoiceOutstanding: "A request for payment that has not been paid would then ask for more than your customer owes. Withdraw that request first.",
  notReversible: "This entry came from an accepted booking amendment and cannot be reversed here. Propose another amendment to change the price.",
  alreadyReversed: "This entry was already reversed.",
} as const;

/** The most a refund may be: money recorded as received that has not already been recorded as returned. */
export function cateringRefundCeilingCents(input: { paidTotalCents: number; adjustments: readonly CateringAdjustmentFact[] }): number {
  return Math.max(0, input.paidTotalCents - sumPosted(input.adjustments, "refund"));
}
/** The most a credit may be: the obligation, so it can reach zero and never go below it. */
export function cateringCreditCeilingCents(position: Pick<CateringLedgerPosition, "obligationCents">): number {
  return Math.max(0, position.obligationCents ?? 0);
}

/**
 * The invariant checked after any change that LOWERS what is owed or what has been received: a live request for
 * payment, less what has been paid, may not exceed what the customer still owes. Paid invoices are history and are
 * never in question; this only stops an UNPAID ask from outliving the obligation that justified it.
 */
export function cateringOutstandingAskFitsPosition(facts: Pick<CateringAdjustmentFacts, "liveInvoicedCents" | "paidTotalCents">, position: CateringLedgerPosition): boolean {
  if (position.obligationCents === null) return true;
  const outstandingAsk = Math.max(0, facts.liveInvoicedCents - facts.paidTotalCents);
  return outstandingAsk <= (position.balanceDueCents ?? 0);
}

export type CateringAdjustmentRequest = { kind: CateringAdjustmentKind; amountCents: number; currency: string; paymentId: string | null };

/**
 * Whether this entry may be posted, judged against the facts the server read under the booking's lock. The server calls
 * it inside the transaction that inserts the row, so every ceiling below is asserted against what the row will sit beside.
 */
export function resolveCateringAdjustment(request: CateringAdjustmentRequest, facts: CateringAdjustmentFacts): { ok: true } | CateringAdjustmentRefusal {
  if (!cateringAdjustmentKindsRecordable(facts.bookingStatus).includes(request.kind)) return refuse("not_allowed_for_status", CATERING_ADJUSTMENT_REFUSAL_COPY.statusKind(request.kind, facts.bookingStatus));
  if (request.currency !== facts.currency) return refuse("currency_mismatch", CATERING_ADJUSTMENT_REFUSAL_COPY.currency);
  const position = deriveCateringLedgerPosition({ agreedTotalCents: facts.agreedTotalCents, paidTotalCents: facts.paidTotalCents, adjustments: facts.adjustments });
  if (request.kind !== "refund") {
    if (position.obligationCents === null) return refuse("no_agreed_price", CATERING_ADJUSTMENT_REFUSAL_COPY.noAgreedPrice);
    if (request.kind === "credit" && request.amountCents > cateringCreditCeilingCents(position)) return refuse("exceeds_obligation", CATERING_ADJUSTMENT_REFUSAL_COPY.creditTooLarge);
    return { ok: true };
  }
  if (request.amountCents > cateringRefundCeilingCents({ paidTotalCents: facts.paidTotalCents, adjustments: facts.adjustments })) return refuse("exceeds_received", CATERING_ADJUSTMENT_REFUSAL_COPY.refundTooLarge);
  if (request.paymentId !== null) {
    const payment = facts.payments.find((row) => row.id === request.paymentId && row.status === "recorded");
    if (!payment) return refuse("payment_not_found", CATERING_ADJUSTMENT_REFUSAL_COPY.paymentNotFound);
    if (payment.currency !== request.currency) return refuse("currency_mismatch", CATERING_ADJUSTMENT_REFUSAL_COPY.currency);
    const already = facts.adjustments.reduce((total, entry) => (cateringAdjustmentCounts(entry) && entry.kind === "refund" && entry.paymentId === payment.id ? total + entry.amountCents : total), 0);
    if (request.amountCents > payment.amountCents - already) return refuse("payment_exceeds", CATERING_ADJUSTMENT_REFUSAL_COPY.paymentTooLarge);
  }
  return { ok: true };
}

/** Whether reversing this posted entry keeps the ledger coherent. */
export function resolveCateringAdjustmentReversal(entry: CateringAdjustmentFact | undefined, facts: CateringAdjustmentFacts): { ok: true } | CateringAdjustmentRefusal {
  if (!entry) return refuse("payment_not_found", "That entry is not on this booking.");
  if (entry.status === "reversed") return refuse("already_reversed", CATERING_ADJUSTMENT_REFUSAL_COPY.alreadyReversed);
  if (entry.source !== "provider_recorded") return refuse("not_reversible", CATERING_ADJUSTMENT_REFUSAL_COPY.notReversible);
  if (!cateringAdjustmentKindsReversible(facts.bookingStatus).includes(entry.kind)) return refuse("not_allowed_for_status", CATERING_ADJUSTMENT_REFUSAL_COPY.statusKind(entry.kind, facts.bookingStatus));
  const after = facts.adjustments.map((row) => (row.id === entry.id ? { ...row, status: "reversed" as const } : row));
  const position = deriveCateringLedgerPosition({ agreedTotalCents: facts.agreedTotalCents, paidTotalCents: facts.paidTotalCents, adjustments: after });
  if (position.obligationCents !== null && position.obligationCents < 0) return refuse("exceeds_obligation", CATERING_ADJUSTMENT_REFUSAL_COPY.creditTooLarge);
  if (!cateringOutstandingAskFitsPosition(facts, position)) return refuse("invoice_outstanding", CATERING_ADJUSTMENT_REFUSAL_COPY.invoiceOutstanding);
  return { ok: true };
}

/**
 * What a Phase 2O price amendment does to the ledger once billing exists, decided from the two stated prices.
 * Currency changes never reach this: they stay refused while any ledger activity exists, because there is no FX here.
 */
export function cateringAmendmentLedgerEffect(basePriceCents: number | null, newPriceCents: number | null): { kind: "charge" | "credit"; amountCents: number } | "unreconcilable" | null {
  if (basePriceCents === null || newPriceCents === null) return "unreconcilable";
  if (newPriceCents === basePriceCents) return null;
  return newPriceCents > basePriceCents
    ? { kind: "charge", amountCents: newPriceCents - basePriceCents }
    : { kind: "credit", amountCents: basePriceCents - newPriceCents };
}

/**
 * Whether the booking's agreed price may move to `newAgreedTotalCents` without leaving the ledger incoherent: the
 * resulting obligation may not be negative and an unpaid request may not outlive it. Paid history is untouched.
 */
export function cateringAmendedPriceKeepsLedgerCoherent(newAgreedTotalCents: number, facts: Pick<CateringAdjustmentFacts, "liveInvoicedCents" | "paidTotalCents" | "adjustments">): boolean {
  const position = deriveCateringLedgerPosition({ agreedTotalCents: newAgreedTotalCents, paidTotalCents: facts.paidTotalCents, adjustments: facts.adjustments });
  return (position.obligationCents ?? 0) >= 0 && cateringOutstandingAskFitsPosition(facts, position);
}

/**
 * Whether a replayed request describes the SAME entry the first attempt posted. A key makes a retry safe; it does not
 * make a retry mean whatever the second request says. Every field that decides what the entry IS is compared.
 */
export function cateringAdjustmentReplayMatches(
  recorded: { kind: string; amountCents: number; currency: string; reason: string; paymentId: string | null; reference: string | null },
  attempt: { kind: string; amountCents: number; currency: string; reason: string; paymentId?: string | null; reference?: string | null },
): boolean {
  return recorded.kind === attempt.kind && recorded.amountCents === attempt.amountCents && recorded.currency === attempt.currency
    && recorded.reason === attempt.reason && (recorded.paymentId ?? null) === (attempt.paymentId ?? null) && (recorded.reference ?? null) === (attempt.reference ?? null);
}

/* ------------------------------------------------------------------------------------------------------------- *
 * Views, paths and copy
 * ------------------------------------------------------------------------------------------------------------- */

/**
 * An entry as either participant sees it. The reason is customer-visible BY DEFINITION (the form says so), so it is
 * shared. `reference` -- the provider's own note on an external refund -- is PROVIDER ONLY, and who recorded or reversed
 * an entry is internal to both.
 */
export type CateringAdjustmentView = {
  id: string;
  kind: CateringAdjustmentKind;
  source: CateringAdjustmentSource;
  status: CateringAdjustmentStatus;
  amountCents: number;
  currency: string;
  reason: string;
  createdAt: string;
  reversedAt: string | null;
  reversalReason: string | null;
  /** The accepted amendment this entry reconciles, when it came from one. */
  amendmentNumber: number | null;
  /** The recorded payment a refund names, when it names one. */
  paymentId: string | null;
  reference?: string | null;
};

export type CateringAdjustmentActions = {
  kinds: CateringAdjustmentKind[];
  reversibleKinds: CateringAdjustmentKind[];
  /** The most a credit / a refund record may be right now, so the form states its own limit. */
  maxCreditCents: number;
  maxRefundCents: number;
};

export const cateringBookingAdjustmentsPath = (bookingId: string) => `/api/catering/bookings/${bookingId}/billing/adjustments`;
export const cateringBookingAdjustmentReversePath = (bookingId: string, entryId: string) => `${cateringBookingAdjustmentsPath(bookingId)}/${entryId}/reverse`;

export const CATERING_ADJUSTMENT_KIND_LABEL: Record<CateringAdjustmentKind, string> = {
  charge: "Additional charge",
  credit: "Credit",
  refund: "Refund recorded",
};

/** The action wording on provider buttons: never "Fix", and a refund is always a RECORD. */
export const CATERING_ADJUSTMENT_ACTION_LABEL: Record<CateringAdjustmentKind, string> = {
  charge: "Add charge",
  credit: "Add credit",
  refund: "Record external refund",
};

/** What each kind does, in the words the confirmation shows before anything is written. */
export const CATERING_ADJUSTMENT_EFFECT_COPY: Record<CateringAdjustmentKind, string> = {
  charge: "Your customer will owe this amount in addition to what they already owe. It is not marked paid, and your existing requests do not change.",
  credit: "This reduces what your customer owes. It does not mean any money was returned.",
  refund: "This records money you have already returned to your customer outside ChefSire. It does not send money.",
};

export const CATERING_REFUND_DISCLOSURE = {
  helper: "Use this after money has been returned outside ChefSire. Recording a refund does not send money.",
  customer: "Refunds shown here are your caterer's record of money returned to you outside ChefSire. ChefSire does not send refunds.",
} as const;

export const CATERING_ADJUSTMENT_STATUS_LABEL: Record<CateringAdjustmentStatus, string> = { posted: "Recorded", reversed: "Reversed" };

export const CATERING_ADJUSTMENT_NOTIFICATIONS = {
  posted: {
    type: "catering_booking_adjustment_posted",
    title: "Your caterer updated your booking's billing",
    message: "Open your booking to see what was added to its billing history.",
  },
  reversed: {
    type: "catering_booking_adjustment_reversed",
    title: "Your caterer reversed a billing entry",
    message: "Open your booking to see the change to its billing history.",
  },
} as const;

/* ------------------------------------------------------------------------------------------------------------- *
 * Request schemas -- integer cents, explicit currency, strict
 * ------------------------------------------------------------------------------------------------------------- */

export const cateringAdjustmentCreateSchema = z.object({
  kind: z.enum(CATERING_ADJUSTMENT_KINDS),
  amountCents: z.number({ invalid_type_error: "Enter the amount in whole cents" }).int("Amount must be a whole number of cents").min(1, "Amount must be more than nothing").max(CATERING_ADJUSTMENT_MAXIMUM_CENTS, "Amount is too large"),
  currency: z.string().trim().regex(/^[A-Z]{3}$/, "Currency must be a 3-letter code"),
  reason: z.string().trim().min(1, "Give your customer a reason").max(CATERING_ADJUSTMENT_REASON_MAX_LENGTH, `The reason can be at most ${CATERING_ADJUSTMENT_REASON_MAX_LENGTH} characters`),
  /** Refunds only: the recorded payment this returns money from. */
  paymentId: z.string().uuid().optional(),
  /** Refunds only, PROVIDER ONLY, and not verified by ChefSire: where the provider kept a note of the return. */
  reference: z.string().trim().min(1).max(CATERING_ADJUSTMENT_REFERENCE_MAX_LENGTH).optional(),
  idempotencyKey: z.string().trim().min(8).max(64),
}).strict().superRefine((value, context) => {
  if (value.kind !== "refund" && (value.paymentId !== undefined || value.reference !== undefined)) {
    context.addIssue({ code: z.ZodIssueCode.custom, message: "A payment and a reference can only be given for a refund record", path: [value.paymentId !== undefined ? "paymentId" : "reference"] });
  }
});
export type CateringAdjustmentCreateInput = z.infer<typeof cateringAdjustmentCreateSchema>;

export const cateringAdjustmentReverseSchema = z.object({
  reason: z.string().trim().min(1, "Give your customer a reason").max(CATERING_ADJUSTMENT_REASON_MAX_LENGTH, `The reason can be at most ${CATERING_ADJUSTMENT_REASON_MAX_LENGTH} characters`),
}).strict();

export const cateringAdjustmentIdSchema = z.string().uuid();

/** The `catering_billing_state` code is shared with Phase 2L; these refine it for the form that is on screen. */
export const CATERING_ADJUSTMENT_REPLAY_CONFLICT_MESSAGE = "This entry was already recorded with different details. Reload to see what was saved, then record any further entry separately.";
