import React from 'react';
import { Activity, Coffee, Droplets, Heart, Shield, Sparkles, Target, Timer, Zap } from 'lucide-react';
import { FilterCard, GoalFilter, m, type WorkoutDrinkRecipe, WorkoutDrinksSubcategoryPage } from '../shared';

export const energyBoosterDrinks: WorkoutDrinkRecipe[] = [
  { id: 'energy-1', name: 'Ashwagandha Golden Latte', description: 'Turmeric, cinnamon, and ashwagandha create a warming caffeine-light ritual drink.', image: 'https://images.unsplash.com/photo-1514995669114-6081e934b693?w=400&h=300&fit=crop', nutrition: { calories: 130, protein: 3, carbs: 16, fat: 6 }, difficulty: 'Easy', prepTime: 6, rating: 4.7, reviews: 276, trending: true, featured: true, tags: ['Ashwagandha', 'Golden latte', 'Adaptogen'], bestTime: 'Anytime or evening without caffeine', goal: 'Stress Resilience', boosterType: 'Latte Style', caffeineLevel: 'None', keyAdaptogen: 'Ashwagandha', ingredients: ['Oat milk', 'Ashwagandha', 'Turmeric', 'Cinnamon', 'Honey'], recipe: { servings: 1, measurements: [m(1, 'cup', 'unsweetened oat milk'), m(1, 'tsp', 'ashwagandha powder'), m(0.25, 'tsp', 'ground turmeric'), m(0.25, 'tsp', 'ground cinnamon'), m(1, 'tsp', 'honey, optional')], directions: ['Warm oat milk gently, then whisk in ashwagandha, turmeric, cinnamon, and honey.', 'Serve hot as a calmer energy ritual or recovery-nightcap alternative.'] } },
  { id: 'energy-2', name: 'Lion’s Mane Mushroom Coffee', description: 'Coffee and lion’s mane pair familiar caffeine with a nootropic-forward mushroom add-in.', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop', nutrition: { calories: 45, protein: 1, carbs: 6, fat: 1 }, difficulty: 'Easy', prepTime: 4, rating: 4.8, reviews: 392, trending: true, featured: true, tags: ['Lion’s mane', 'Coffee', 'Focus'], bestTime: 'Morning focus block', goal: 'Focus', boosterType: 'Coffee Based', caffeineLevel: 'High (~150mg)', keyAdaptogen: 'Lion’s mane', ingredients: ['Brewed coffee', 'Lion’s mane powder', 'Collagen or milk', 'Maple syrup'], recipe: { servings: 1, measurements: [m(1, 'cup', 'hot brewed coffee'), m(1, 'tsp', 'lion’s mane powder'), m(2, 'tbsp', 'milk or collagen creamer'), m(1, 'tsp', 'maple syrup, optional')], directions: ['Blend or froth hot coffee with lion’s mane, milk, and maple syrup until lightly foamy.', 'Use in the morning when you want focus with your regular coffee ritual.'] } },
  { id: 'energy-3', name: 'Maca Cacao Energy Bomb', description: 'Cacao, maca, and milk deliver a deeper chocolate flavor with gentle stimulation.', image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop', nutrition: { calories: 190, protein: 7, carbs: 21, fat: 8 }, difficulty: 'Easy', prepTime: 5, rating: 4.9, reviews: 241, featured: true, tags: ['Maca', 'Cacao', 'Steady energy'], bestTime: 'Mid-morning or pre-workout', goal: 'Steady Energy', boosterType: 'Latte Style', caffeineLevel: 'Moderate (~70mg)', keyAdaptogen: 'Maca', ingredients: ['Milk', 'Cacao powder', 'Maca powder', 'Date'], recipe: { servings: 1, measurements: [m(1, 'cup', '2% milk or soy milk'), m(1, 'tbsp', 'unsweetened cacao powder'), m(1, 'tsp', 'maca powder'), m(1, 'small', 'Medjool date, pitted')], directions: ['Blend warmed or chilled milk with cacao, maca, and date until smooth.', 'Drink before a training block or during an afternoon slump when you prefer chocolate over coffee.'] } },
  { id: 'energy-4', name: 'Cordyceps Pre-Performance Tonic', description: 'Cordyceps, citrus, and ginger create a bright food-first performance sip.', image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&h=300&fit=crop', nutrition: { calories: 60, protein: 1, carbs: 13, fat: 0 }, difficulty: 'Easy', prepTime: 4, rating: 4.6, reviews: 187, tags: ['Cordyceps', 'Performance', 'Citrus'], bestTime: '30-45 min before training', goal: 'Performance Support', boosterType: 'Citrus Elixir', caffeineLevel: 'None', keyAdaptogen: 'Cordyceps', ingredients: ['Orange juice', 'Water', 'Cordyceps powder', 'Ginger'], recipe: { servings: 1, measurements: [m(0.5, 'cup', 'orange juice'), m(0.5, 'cup', 'cold water'), m(1, 'tsp', 'cordyceps powder'), m(0.25, 'tsp', 'grated ginger')], directions: ['Shake orange juice, water, cordyceps, and ginger in a jar until evenly combined.', 'Serve chilled before training or competition days when you want a non-caffeinated booster.'] } },
  { id: 'energy-5', name: 'Rhodiola Citrus Stress Shield', description: 'Rhodiola and grapefruit create a tart, midday resilience drink.', image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=400&h=300&fit=crop', nutrition: { calories: 55, protein: 0, carbs: 12, fat: 0 }, difficulty: 'Easy', prepTime: 3, rating: 4.5, reviews: 143, trending: true, tags: ['Rhodiola', 'Citrus', 'Stress resilience'], bestTime: 'Midday or pre-meeting', goal: 'Stress Resilience', boosterType: 'Citrus Elixir', caffeineLevel: 'None', keyAdaptogen: 'Rhodiola', ingredients: ['Grapefruit juice', 'Water', 'Rhodiola tincture', 'Honey'], recipe: { servings: 1, measurements: [m(0.5, 'cup', 'grapefruit juice'), m(0.5, 'cup', 'cold water'), m(1, 'dropper', 'rhodiola tincture'), m(1, 'tsp', 'honey, optional')], directions: ['Stir grapefruit juice, water, rhodiola, and honey until combined.', 'Sip on demanding work or training days when you want a botanical lift without caffeine.'] } },
  { id: 'energy-6', name: 'Schisandra Berry Energy Elixir', description: 'Schisandra and berry tea make a tart antioxidant-rich tonic.', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&h=300&fit=crop', nutrition: { calories: 40, protein: 0, carbs: 10, fat: 0 }, difficulty: 'Easy', prepTime: 5, rating: 4.6, reviews: 129, featured: true, tags: ['Schisandra', 'Berry tea', 'Adaptogens'], bestTime: 'Anytime pick-me-up', goal: 'Steady Energy', boosterType: 'Citrus Elixir', caffeineLevel: 'Moderate (~70mg)', keyAdaptogen: 'Schisandra', ingredients: ['Berry tea', 'Schisandra powder', 'Lemon juice', 'Honey'], recipe: { servings: 1, measurements: [m(1, 'cup', 'strong berry tea, chilled'), m(0.5, 'tsp', 'schisandra powder'), m(1, 'tbsp', 'fresh lemon juice'), m(1, 'tsp', 'honey, optional')], directions: ['Whisk schisandra into chilled berry tea, then add lemon and honey.', 'Serve over ice for a tart, lightly caffeinated afternoon booster.'] } },
];

const typeCards: FilterCard[] = [
  { id: 'latte-style', name: 'Latte Style', description: 'Warm, comforting drinks built around spices, mushrooms, or cacao.', icon: Coffee, detailA: 'Best for', detailAValue: 'Morning ritual energy', detailB: 'Timing', detailBValue: 'Anytime' },
  { id: 'coffee-based', name: 'Coffee Based', description: 'Coffee paired with mushrooms or herbs for added focus support.', icon: Zap, detailA: 'Best for', detailAValue: 'Mental performance', detailB: 'Timing', detailBValue: 'Morning to midday' },
  { id: 'citrus-elixir', name: 'Citrus Elixir', description: 'Brighter drinks that lean on botanicals instead of heavy dairy.', icon: Activity, detailA: 'Best for', detailAValue: 'Stress-heavy days', detailB: 'Timing', detailBValue: 'Midday or pre-workout' },
];

const goalFilters: GoalFilter[] = [
  { id: 'focus', name: 'Focus', icon: Target, color: 'text-purple-600' },
  { id: 'stress-resilience', name: 'Stress Resilience', icon: Shield, color: 'text-fuchsia-600' },
  { id: 'steady-energy', name: 'Steady Energy', icon: Zap, color: 'text-violet-600' },
  { id: 'performance-support', name: 'Performance Support', icon: Activity, color: 'text-indigo-600' },
];

export default function EnergyBoosterDrinksPage() {
  return <WorkoutDrinksSubcategoryPage title="Energy Booster Drinks" backHref="/drinks/workout-drinks" backLabel="Back to Workout Drinks" badgeText="Adaptogen Boosters" shareText="Explore ChefSire energy booster drinks with adaptogens, mushrooms, and nootropic-friendly ingredients." accent="purple" icon={Sparkles} sourceRoute="/drinks/workout-drinks/energy-boosters" recipes={energyBoosterDrinks} typeTabLabel="Adaptogen Types" typeLabel="Adaptogen Types" typeField="boosterType" typeCards={typeCards} goalFilters={goalFilters} crossSubcategories={[{ id: 'pre-workout', name: 'Pre-Workout', description: 'Prime your training session', route: '/drinks/workout-drinks/pre-workout', icon: Timer }, { id: 'post-workout', name: 'Post-Workout', description: 'Protein and recovery blends', route: '/drinks/workout-drinks/post-workout', icon: Heart }, { id: 'hydration', name: 'Hydration', description: 'Electrolyte-focused drinks', route: '/drinks/workout-drinks/hydration', icon: Droplets }]} stats={{ first: { value: '4.7★', label: 'Avg Rating', color: 'text-purple-600' }, second: { value: '4 min', label: 'Avg Prep', color: 'text-fuchsia-600' }, third: { value: '4', label: 'Featured Picks', color: 'text-violet-600' } }} searchPlaceholder="Search energy booster drinks..." primaryStat={{ label: 'Adaptogen', key: 'keyAdaptogen', color: 'text-purple-600' }} footer={{ labelA: 'Caffeine', keyA: 'caffeineLevel', colorA: 'text-purple-600', labelB: 'Best Window', keyB: 'bestTime', colorB: 'text-fuchsia-600' }} buttonLabel="Brew Booster" />;
}
