import React from 'react';
import { Activity, Coffee, Droplets, Heart, Leaf, Sparkles, Sun, Timer } from 'lucide-react';
import { FilterCard, GoalFilter, m, type WorkoutDrinkRecipe, WorkoutDrinksSubcategoryPage } from '../shared';

export const hydrationDrinks: WorkoutDrinkRecipe[] = [
  { id: 'hydration-1', name: 'DIY Sports Drink', description: 'A homemade carbohydrate-electrolyte drink for longer sessions or summer training.', image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop', nutrition: { calories: 70, protein: 0, carbs: 18, fat: 0 }, difficulty: 'Easy', prepTime: 3, rating: 4.8, reviews: 402, trending: true, featured: true, tags: ['Homemade sports drink', 'Electrolytes', 'Training'], bestTime: 'Before or during long workouts', goal: 'Electrolyte Balance', hydrationType: 'Sports Drink', sodiumMg: 290, ingredients: ['Water', 'Orange juice', 'Honey', 'Sea salt'], recipe: { servings: 1, measurements: [m(1.5, 'cup', 'cold water'), m(0.5, 'cup', 'orange juice'), m(1, 'tbsp', 'honey'), m(0.125, 'tsp', 'sea salt', 'Roughly 250-300 mg sodium depending on salt type')], directions: ['Shake water, orange juice, honey, and salt until dissolved.', 'Chill and use during sessions that last longer than an hour.'] } },
  { id: 'hydration-2', name: 'Watermelon Mint Hydrator', description: 'Watermelon and mint deliver refreshing flavor with naturally occurring potassium.', image: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&h=300&fit=crop', nutrition: { calories: 55, protein: 1, carbs: 13, fat: 0 }, difficulty: 'Easy', prepTime: 5, rating: 4.7, reviews: 265, trending: true, featured: true, tags: ['Watermelon', 'Mint', 'Cooling'], bestTime: 'Before outdoor training', goal: 'Heat Relief', hydrationType: 'Produce Forward', sodiumMg: 140, ingredients: ['Watermelon', 'Water', 'Mint', 'Lime', 'Salt'], recipe: { servings: 1, measurements: [m(1, 'cup', 'watermelon cubes'), m(0.75, 'cup', 'cold water'), m(4, 'leaves', 'mint'), m(1, 'tbsp', 'lime juice'), m(1, 'pinch', 'sea salt')], directions: ['Blend watermelon, water, mint, lime, and salt until smooth.', 'Serve over ice as a cooling hydrator before or after outdoor sessions.'] } },
  { id: 'hydration-3', name: 'Coconut Mango Electrolyte Slush', description: 'A frozen tropical slush with potassium-rich coconut water and mango.', image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=400&h=300&fit=crop', nutrition: { calories: 95, protein: 1, carbs: 23, fat: 0 }, difficulty: 'Easy', prepTime: 5, rating: 4.9, reviews: 318, featured: true, tags: ['Coconut water', 'Mango', 'Slush'], bestTime: 'After hot workouts', goal: 'Heat Relief', hydrationType: 'Produce Forward', sodiumMg: 110, ingredients: ['Coconut water', 'Frozen mango', 'Lime juice', 'Pinch of salt'], recipe: { servings: 1, measurements: [m(1, 'cup', 'coconut water'), m(0.75, 'cup', 'frozen mango'), m(1, 'tbsp', 'lime juice'), m(1, 'pinch', 'sea salt')], directions: ['Blend coconut water, frozen mango, lime juice, and salt until slushy.', 'Drink after long runs or court sessions when you want a cold texture.'] } },
  { id: 'hydration-4', name: 'Pink Salt Lemon Rehydrator', description: 'A minimalist lemon-salt blend that works well when appetite is low.', image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&h=300&fit=crop', nutrition: { calories: 35, protein: 0, carbs: 9, fat: 0 }, difficulty: 'Easy', prepTime: 2, rating: 4.5, reviews: 188, tags: ['Lemon', 'Salt', 'Simple'], bestTime: 'First thing after sweat loss', goal: 'Electrolyte Balance', hydrationType: 'Sports Drink', sodiumMg: 300, ingredients: ['Water', 'Lemon juice', 'Maple syrup', 'Pink salt'], recipe: { servings: 1, measurements: [m(1.5, 'cup', 'cold water'), m(2, 'tbsp', 'fresh lemon juice'), m(2, 'tsp', 'maple syrup'), m(0.125, 'tsp', 'Himalayan pink salt')], directions: ['Stir water, lemon juice, maple syrup, and salt until the crystals dissolve.', 'Use after sweaty sessions when you need fluid and sodium without a heavy drink.'] } },
  { id: 'hydration-5', name: 'Green Tea Electrolyte Cooler', description: 'Lightly caffeinated green tea with citrus and sodium for a gentle lift.', image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=300&fit=crop', nutrition: { calories: 40, protein: 0, carbs: 10, fat: 0 }, difficulty: 'Easy', prepTime: 6, rating: 4.6, reviews: 224, trending: true, tags: ['Green tea', 'Electrolytes', 'Cooling'], bestTime: 'Pre-workout or during afternoon training', goal: 'Endurance', hydrationType: 'Tea + Electrolytes', sodiumMg: 180, ingredients: ['Brewed green tea', 'Honey', 'Lemon', 'Salt'], recipe: { servings: 1, measurements: [m(1, 'cup', 'brewed green tea, chilled'), m(1, 'tsp', 'honey'), m(1, 'tbsp', 'fresh lemon juice'), m(1, 'pinch', 'sea salt')], directions: ['Whisk honey and salt into chilled green tea, then add lemon juice.', 'Serve over ice when you want a modest caffeine bump plus hydration.'] } },
  { id: 'hydration-6', name: 'Cucumber Celery Hydration Juice', description: 'A savory-leaning juice with produce rich in water and potassium.', image: 'https://images.unsplash.com/photo-1622484211443-76c4deea5047?w=400&h=300&fit=crop', nutrition: { calories: 45, protein: 1, carbs: 9, fat: 0 }, difficulty: 'Easy', prepTime: 6, rating: 4.4, reviews: 161, tags: ['Cucumber', 'Celery', 'Hydration'], bestTime: 'Anytime hydration support', goal: 'Daily Hydration', hydrationType: 'Produce Forward', sodiumMg: 160, ingredients: ['Cucumber', 'Celery', 'Lemon juice', 'Water', 'Salt'], recipe: { servings: 1, measurements: [m(1, 'cup', 'cucumber chunks'), m(0.5, 'cup', 'celery pieces'), m(1, 'tbsp', 'fresh lemon juice'), m(0.5, 'cup', 'cold water'), m(1, 'pinch', 'sea salt')], directions: ['Blend cucumber, celery, lemon juice, water, and salt until smooth, then strain if desired.', 'Sip between meals or after low-intensity sessions for a lighter hydration option.'] } },
];

const typeCards: FilterCard[] = [
  { id: 'sports-drink', name: 'Sports Drink', description: 'Simple carbohydrate-electrolyte blends for longer or hotter sessions.', icon: Droplets, detailA: 'Best for', detailAValue: '60+ min efforts', detailB: 'Timing', detailBValue: 'Before and during' },
  { id: 'produce-forward', name: 'Produce Forward', description: 'Water-rich fruits and vegetables layer fluids with flavor.', icon: Leaf, detailA: 'Best for', detailAValue: 'Low intensity or recovery days', detailB: 'Timing', detailBValue: 'Anytime' },
  { id: 'tea-electrolyte', name: 'Tea + Electrolytes', description: 'Light caffeine plus sodium for a gentler hydration boost.', icon: Coffee, detailA: 'Best for', detailAValue: 'Afternoon training', detailB: 'Timing', detailBValue: 'Pre or during' },
];

const goalFilters: GoalFilter[] = [
  { id: 'electrolyte-balance', name: 'Electrolyte Balance', icon: Droplets, color: 'text-cyan-600' },
  { id: 'heat-relief', name: 'Heat Relief', icon: Sun, color: 'text-sky-600' },
  { id: 'endurance', name: 'Endurance', icon: Activity, color: 'text-blue-600' },
  { id: 'daily-hydration', name: 'Daily Hydration', icon: Leaf, color: 'text-teal-600' },
];

export default function HydrationDrinksPage() {
  return <WorkoutDrinksSubcategoryPage title="Hydration Drinks" backHref="/drinks/workout-drinks" backLabel="Back to Workout Drinks" badgeText="Hydration Focus" shareText="Explore ChefSire hydration drinks for electrolytes, cooling fluids, and endurance support." accent="cyan" icon={Droplets} sourceRoute="/drinks/workout-drinks/hydration" recipes={hydrationDrinks} typeTabLabel="Hydration Types" typeLabel="Hydration Types" typeField="hydrationType" typeCards={typeCards} goalFilters={goalFilters} crossSubcategories={[{ id: 'pre-workout', name: 'Pre-Workout', description: 'Prime your training session', route: '/drinks/workout-drinks/pre-workout', icon: Timer }, { id: 'post-workout', name: 'Post-Workout', description: 'Protein and recovery blends', route: '/drinks/workout-drinks/post-workout', icon: Heart }, { id: 'energy-boosters', name: 'Energy Boosters', description: 'Adaptogens and nootropics', route: '/drinks/workout-drinks/energy-boosters', icon: Sparkles }]} stats={{ first: { value: '180mg+', label: 'Avg Sodium', color: 'text-cyan-600' }, second: { value: '4.7★', label: 'Avg Rating', color: 'text-sky-600' }, third: { value: '5 min', label: 'Avg Prep', color: 'text-purple-600' } }} searchPlaceholder="Search hydration drinks..." primaryStat={{ label: 'Sodium', key: 'sodiumMg', color: 'text-cyan-600', suffix: 'mg' }} footer={{ labelA: 'Hydration', keyA: 'hydrationType', colorA: 'text-cyan-600', labelB: 'Best Window', keyB: 'bestTime', colorB: 'text-sky-600' }} buttonLabel="Mix Hydrator" />;
}
