export type NutritionCampaignDifficulty = "beginner" | "intermediate" | "advanced";
export type NutritionCampaignPrepIntensity = "light" | "moderate" | "high";
export type NutritionCampaignBudget = "student" | "budget" | "balanced" | "premium";
export type NutritionDietType =
  | "high-protein"
  | "fat-loss"
  | "vegan"
  | "mediterranean"
  | "family"
  | "athlete"
  | "keto"
  | "meal-prep"
  | "student"
  | "anti-inflammatory";

export interface NutritionCampaignCreator {
  id: string;
  name: string;
  handle: string;
  avatarUrl: string;
  specialty: string;
  followers: number;
  campaignCount: number;
  consistencyScore: number;
  isFeatured: boolean;
}

export interface NutritionCampaignMacros {
  caloriesPerDay: number;
  proteinPerDay: number;
  carbsPerDay: number;
  fatPerDay: number;
}

export interface NutritionCampaign {
  id: string;
  title: string;
  subtitle: string;
  coverImageUrl: string;
  creator: NutritionCampaignCreator;
  dietType: NutritionDietType;
  macros: NutritionCampaignMacros;
  durationDays: number;
  difficulty: NutritionCampaignDifficulty;
  budgetLevel: NutritionCampaignBudget;
  estimatedBudget: string;
  prepIntensity: NutritionCampaignPrepIntensity;
  saves: number;
  remixes: number;
  completionRate: number;
  tags: string[];
  seasonalTags: string[];
  category: string;
  isTrending: boolean;
  isNew: boolean;
  isFeatured: boolean;
}

export const nutritionCampaigns: NutritionCampaign[] = [
  {
    id: "lean-athlete-reset",
    title: "Lean Athlete Reset",
    subtitle: "High-protein performance meals built for strength blocks and clean recovery.",
    coverImageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "maya-strength",
      name: "Maya Chen",
      handle: "mayamacros",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
      specialty: "High protein coach",
      followers: 48200,
      campaignCount: 18,
      consistencyScore: 96,
      isFeatured: true,
    },
    dietType: "athlete",
    macros: { caloriesPerDay: 2450, proteinPerDay: 185, carbsPerDay: 245, fatPerDay: 74 },
    durationDays: 28,
    difficulty: "intermediate",
    budgetLevel: "balanced",
    estimatedBudget: "$92/week",
    prepIntensity: "moderate",
    saves: 12840,
    remixes: 1830,
    completionRate: 84,
    tags: ["strength", "recovery", "high protein"],
    seasonalTags: ["spring training", "gym reset"],
    category: "Athlete",
    isTrending: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "coastal-mediterranean-cut",
    title: "Coastal Mediterranean Cut",
    subtitle: "Bright bowls, seafood-forward dinners, and a gentle deficit without diet fatigue.",
    coverImageUrl: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "eleni-table",
      name: "Eleni Voss",
      handle: "eleni.eats",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80",
      specialty: "Mediterranean strategist",
      followers: 37100,
      campaignCount: 14,
      consistencyScore: 93,
      isFeatured: true,
    },
    dietType: "mediterranean",
    macros: { caloriesPerDay: 1750, proteinPerDay: 132, carbsPerDay: 165, fatPerDay: 62 },
    durationDays: 21,
    difficulty: "beginner",
    budgetLevel: "balanced",
    estimatedBudget: "$88/week",
    prepIntensity: "light",
    saves: 10920,
    remixes: 1422,
    completionRate: 89,
    tags: ["fat loss", "omega-3", "fresh prep"],
    seasonalTags: ["summer shred", "coastal"],
    category: "Fat Loss",
    isTrending: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "vegan-prep-powerhouse",
    title: "Vegan Prep Powerhouse",
    subtitle: "Plant-based batch cooking with complete proteins, fiber, and colorful sauces.",
    coverImageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "nora-plants",
      name: "Nora Fields",
      handle: "plantprep.nora",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
      specialty: "Vegan prep expert",
      followers: 59600,
      campaignCount: 22,
      consistencyScore: 98,
      isFeatured: true,
    },
    dietType: "vegan",
    macros: { caloriesPerDay: 2050, proteinPerDay: 118, carbsPerDay: 258, fatPerDay: 61 },
    durationDays: 14,
    difficulty: "intermediate",
    budgetLevel: "budget",
    estimatedBudget: "$64/week",
    prepIntensity: "high",
    saves: 15440,
    remixes: 2405,
    completionRate: 81,
    tags: ["vegan", "batch cook", "fiber"],
    seasonalTags: ["earth month", "pantry smart"],
    category: "Vegan",
    isTrending: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "family-budget-protein",
    title: "Family Budget Protein",
    subtitle: "Four-serving dinners, smart leftovers, and affordable macro anchors for busy homes.",
    coverImageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "ben-family",
      name: "Ben Alvarez",
      handle: "budgetdadplates",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
      specialty: "Budget family planner",
      followers: 42100,
      campaignCount: 16,
      consistencyScore: 91,
      isFeatured: true,
    },
    dietType: "family",
    macros: { caloriesPerDay: 2150, proteinPerDay: 150, carbsPerDay: 228, fatPerDay: 70 },
    durationDays: 30,
    difficulty: "beginner",
    budgetLevel: "budget",
    estimatedBudget: "$58/week",
    prepIntensity: "moderate",
    saves: 13110,
    remixes: 1977,
    completionRate: 86,
    tags: ["family", "leftovers", "budget"],
    seasonalTags: ["back to school", "weeknight"],
    category: "Family Budget",
    isTrending: false,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "keto-clean-launch",
    title: "Keto Clean Launch",
    subtitle: "A structured low-carb runway with whole-food fats and electrolyte-aware prep.",
    coverImageUrl: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "sloane-keto",
      name: "Sloane Reed",
      handle: "sloaneketo",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80",
      specialty: "Low-carb systems",
      followers: 28700,
      campaignCount: 11,
      consistencyScore: 88,
      isFeatured: false,
    },
    dietType: "keto",
    macros: { caloriesPerDay: 1900, proteinPerDay: 138, carbsPerDay: 42, fatPerDay: 132 },
    durationDays: 21,
    difficulty: "advanced",
    budgetLevel: "premium",
    estimatedBudget: "$118/week",
    prepIntensity: "moderate",
    saves: 7680,
    remixes: 702,
    completionRate: 73,
    tags: ["keto", "low carb", "whole food"],
    seasonalTags: ["new year reset"],
    category: "Keto",
    isTrending: false,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "student-macro-starter",
    title: "Student Macro Starter",
    subtitle: "Microwave-friendly, portable meals that keep protein high and grocery spend low.",
    coverImageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "jay-campus",
      name: "Jay Patel",
      handle: "campusmacros",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80",
      specialty: "Student budget builder",
      followers: 22600,
      campaignCount: 9,
      consistencyScore: 90,
      isFeatured: false,
    },
    dietType: "student",
    macros: { caloriesPerDay: 2250, proteinPerDay: 142, carbsPerDay: 280, fatPerDay: 58 },
    durationDays: 14,
    difficulty: "beginner",
    budgetLevel: "student",
    estimatedBudget: "$43/week",
    prepIntensity: "light",
    saves: 9200,
    remixes: 1590,
    completionRate: 82,
    tags: ["student", "microwave", "portable"],
    seasonalTags: ["semester prep", "dorm friendly"],
    category: "Student Budget",
    isTrending: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "anti-inflammatory-glow",
    title: "Anti-Inflammatory Glow",
    subtitle: "Color-dense plates with polyphenols, steady energy, and low-friction prep rituals.",
    coverImageUrl: "https://images.unsplash.com/photo-1495546968767-f0573cca821e?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "dr-iman",
      name: "Iman Brooks",
      handle: "glowplate.lab",
      avatarUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=256&q=80",
      specialty: "Anti-inflammatory educator",
      followers: 33400,
      campaignCount: 13,
      consistencyScore: 95,
      isFeatured: true,
    },
    dietType: "anti-inflammatory",
    macros: { caloriesPerDay: 1850, proteinPerDay: 125, carbsPerDay: 205, fatPerDay: 61 },
    durationDays: 28,
    difficulty: "beginner",
    budgetLevel: "balanced",
    estimatedBudget: "$82/week",
    prepIntensity: "light",
    saves: 11230,
    remixes: 988,
    completionRate: 90,
    tags: ["anti-inflammatory", "color", "energy"],
    seasonalTags: ["spring reset", "immune support"],
    category: "Wellness",
    isTrending: false,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "five-day-prep-engine",
    title: "5-Day Prep Engine",
    subtitle: "A Sunday prep operating system with modular bowls, sauces, and breakfast lanes.",
    coverImageUrl: "https://images.unsplash.com/photo-1543353071-10c8ba85a904?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "tessa-prep",
      name: "Tessa Moore",
      handle: "prepengine",
      avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=256&q=80",
      specialty: "Meal prep architect",
      followers: 51200,
      campaignCount: 20,
      consistencyScore: 97,
      isFeatured: true,
    },
    dietType: "meal-prep",
    macros: { caloriesPerDay: 2000, proteinPerDay: 155, carbsPerDay: 210, fatPerDay: 63 },
    durationDays: 35,
    difficulty: "intermediate",
    budgetLevel: "balanced",
    estimatedBudget: "$76/week",
    prepIntensity: "high",
    saves: 16790,
    remixes: 3188,
    completionRate: 78,
    tags: ["meal prep", "modular", "batch cook"],
    seasonalTags: ["sunday system"],
    category: "Meal Prep",
    isTrending: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "desk-lunch-fat-loss",
    title: "Desk Lunch Fat Loss",
    subtitle: "No-sad-desk-lunch templates that travel well and keep hunger stable.",
    coverImageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "claire-office",
      name: "Claire Stone",
      handle: "deskfuel",
      avatarUrl: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=256&q=80",
      specialty: "Office nutrition creator",
      followers: 19100,
      campaignCount: 7,
      consistencyScore: 87,
      isFeatured: false,
    },
    dietType: "fat-loss",
    macros: { caloriesPerDay: 1650, proteinPerDay: 128, carbsPerDay: 154, fatPerDay: 52 },
    durationDays: 21,
    difficulty: "beginner",
    budgetLevel: "budget",
    estimatedBudget: "$61/week",
    prepIntensity: "moderate",
    saves: 6880,
    remixes: 861,
    completionRate: 85,
    tags: ["fat loss", "lunch", "office"],
    seasonalTags: ["workweek reset"],
    category: "Fat Loss",
    isTrending: false,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "marathon-carb-smart",
    title: "Marathon Carb Smart",
    subtitle: "Periodized carbs, recovery proteins, and race-week confidence for endurance athletes.",
    coverImageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "leo-run",
      name: "Leo Grant",
      handle: "runfuel.studio",
      avatarUrl: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=256&q=80",
      specialty: "Endurance nutrition",
      followers: 30500,
      campaignCount: 12,
      consistencyScore: 92,
      isFeatured: false,
    },
    dietType: "athlete",
    macros: { caloriesPerDay: 2850, proteinPerDay: 158, carbsPerDay: 388, fatPerDay: 74 },
    durationDays: 42,
    difficulty: "advanced",
    budgetLevel: "premium",
    estimatedBudget: "$124/week",
    prepIntensity: "moderate",
    saves: 5890,
    remixes: 518,
    completionRate: 76,
    tags: ["endurance", "carb cycling", "race week"],
    seasonalTags: ["race season"],
    category: "Athlete",
    isTrending: false,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "vegan-muscle-stack",
    title: "Vegan Muscle Stack",
    subtitle: "Tofu, tempeh, seitan, and legume rotations for plant-based lean mass.",
    coverImageUrl: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "nora-plants",
      name: "Nora Fields",
      handle: "plantprep.nora",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
      specialty: "Vegan prep expert",
      followers: 59600,
      campaignCount: 22,
      consistencyScore: 98,
      isFeatured: true,
    },
    dietType: "vegan",
    macros: { caloriesPerDay: 2550, proteinPerDay: 145, carbsPerDay: 318, fatPerDay: 72 },
    durationDays: 28,
    difficulty: "advanced",
    budgetLevel: "balanced",
    estimatedBudget: "$84/week",
    prepIntensity: "high",
    saves: 8120,
    remixes: 1134,
    completionRate: 74,
    tags: ["vegan", "muscle gain", "high protein"],
    seasonalTags: ["bulk season"],
    category: "Vegan",
    isTrending: false,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "med-family-table",
    title: "Mediterranean Family Table",
    subtitle: "Family-style dinners with kid-friendly sides and balanced adult macro options.",
    coverImageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "ben-family",
      name: "Ben Alvarez",
      handle: "budgetdadplates",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
      specialty: "Budget family planner",
      followers: 42100,
      campaignCount: 16,
      consistencyScore: 91,
      isFeatured: true,
    },
    dietType: "mediterranean",
    macros: { caloriesPerDay: 2100, proteinPerDay: 138, carbsPerDay: 235, fatPerDay: 68 },
    durationDays: 28,
    difficulty: "beginner",
    budgetLevel: "budget",
    estimatedBudget: "$67/week",
    prepIntensity: "moderate",
    saves: 7340,
    remixes: 944,
    completionRate: 88,
    tags: ["mediterranean", "family", "weeknight"],
    seasonalTags: ["family reset"],
    category: "Family Budget",
    isTrending: false,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "premium-glucose-steady",
    title: "Glucose-Steady Premium",
    subtitle: "Chef-grade meals organized around protein-first sequencing and steady energy.",
    coverImageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "dr-iman",
      name: "Iman Brooks",
      handle: "glowplate.lab",
      avatarUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=256&q=80",
      specialty: "Anti-inflammatory educator",
      followers: 33400,
      campaignCount: 13,
      consistencyScore: 95,
      isFeatured: true,
    },
    dietType: "anti-inflammatory",
    macros: { caloriesPerDay: 1950, proteinPerDay: 142, carbsPerDay: 172, fatPerDay: 76 },
    durationDays: 21,
    difficulty: "intermediate",
    budgetLevel: "premium",
    estimatedBudget: "$132/week",
    prepIntensity: "light",
    saves: 4720,
    remixes: 403,
    completionRate: 83,
    tags: ["steady energy", "premium", "low glycemic"],
    seasonalTags: ["executive reset"],
    category: "Wellness",
    isTrending: false,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "simple-keto-weeknights",
    title: "Simple Keto Weeknights",
    subtitle: "Fast low-carb dinners with repeatable grocery patterns and minimal tracking friction.",
    coverImageUrl: "https://images.unsplash.com/photo-1523986371872-9d3ba2e2a389?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "sloane-keto",
      name: "Sloane Reed",
      handle: "sloaneketo",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80",
      specialty: "Low-carb systems",
      followers: 28700,
      campaignCount: 11,
      consistencyScore: 88,
      isFeatured: false,
    },
    dietType: "keto",
    macros: { caloriesPerDay: 1800, proteinPerDay: 132, carbsPerDay: 38, fatPerDay: 124 },
    durationDays: 14,
    difficulty: "beginner",
    budgetLevel: "balanced",
    estimatedBudget: "$79/week",
    prepIntensity: "light",
    saves: 5580,
    remixes: 610,
    completionRate: 80,
    tags: ["keto", "quick dinners", "low carb"],
    seasonalTags: ["weeknight"],
    category: "Keto",
    isTrending: false,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "budget-bulk-basics",
    title: "Budget Bulk Basics",
    subtitle: "Calorie surplus meals that lean on pantry staples, frozen veg, and repeatable proteins.",
    coverImageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "jay-campus",
      name: "Jay Patel",
      handle: "campusmacros",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80",
      specialty: "Student budget builder",
      followers: 22600,
      campaignCount: 9,
      consistencyScore: 90,
      isFeatured: false,
    },
    dietType: "high-protein",
    macros: { caloriesPerDay: 3050, proteinPerDay: 176, carbsPerDay: 402, fatPerDay: 82 },
    durationDays: 30,
    difficulty: "intermediate",
    budgetLevel: "student",
    estimatedBudget: "$55/week",
    prepIntensity: "high",
    saves: 6410,
    remixes: 890,
    completionRate: 77,
    tags: ["bulking", "budget", "high protein"],
    seasonalTags: ["winter bulk"],
    category: "High Protein",
    isTrending: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "minimal-prep-cut",
    title: "Minimal Prep Cut",
    subtitle: "A low-cooking fat-loss system with assembly meals, smart snacks, and protein defaults.",
    coverImageUrl: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=1200&q=80",
    creator: {
      id: "maya-strength",
      name: "Maya Chen",
      handle: "mayamacros",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
      specialty: "High protein coach",
      followers: 48200,
      campaignCount: 18,
      consistencyScore: 96,
      isFeatured: true,
    },
    dietType: "fat-loss",
    macros: { caloriesPerDay: 1550, proteinPerDay: 140, carbsPerDay: 126, fatPerDay: 54 },
    durationDays: 14,
    difficulty: "beginner",
    budgetLevel: "balanced",
    estimatedBudget: "$72/week",
    prepIntensity: "light",
    saves: 8850,
    remixes: 1202,
    completionRate: 87,
    tags: ["fat loss", "minimal prep", "high protein"],
    seasonalTags: ["summer ready"],
    category: "Fat Loss",
    isTrending: true,
    isNew: true,
    isFeatured: false,
  },
];

export const featuredNutritionCreators = Array.from(
  new Map(nutritionCampaigns.map((campaign) => [campaign.creator.id, campaign.creator])).values(),
).filter((creator) => creator.isFeatured);
